### PR TITLE
Fix BTD/Scrape Flush Count with Filters

### LINKED ISSUE #4604: Backtransform diagnostics crash when filters remove all particles
PR #4570 added particle filters to the Backtransformed diagnostics. 
However, when the filters are such that they eliminate all particles, the code crashes with the following error:
```
A Record can not be written without any contained RecordComponents: id
```

Reproducer:
[inputs_3d.txt](https://github.com/ECP-WarpX/WarpX/files/13894175/inputs_3d.txt)
(identical to [this test](https://github.com/ECP-WarpX/WarpX/blob/development/Examples/Tests/boosted_diags/inputs_3d), but with `diag2.beam.random_fraction = 0` to remove all particles)

### PR DESCRIPTION
**Pull request by ax3l**
Move the counting of already flushed particles for writers that call the I/O backends multiple time per data set, e.g., BTD and boundary scraping, into the I/O backend.

Currently (until #4420), filtering is done as the first step in I/O backends and thus the previous count outside of the I/O backends was over-counting particles that might still get filtered out.

Regression to #4570.

Fix #4604.

### CODE REVIEW

File: Source/Diagnostics/BTDiagnostics.H [hunk 1]
```diff
@@ -399,8 +399,6 @@ private:
         lab-frame data. */
     void InitializeParticleFunctors () override;
 
-    /** Update total number of particles flushed for all species for ith snapshot */
-    void UpdateTotalParticlesFlushed(int i_buffer);
```
Comment (ax3l) [inline Source/Diagnostics/BTDiagnostics.H:403]: Removed and delegated to the I/O backend, which currently does the filtering and thus knows what number of particles is truly written.

**Comment by ax3l** [comment]
cc @roelof-groenewald just FYI for scraping with filters

**Comment by ax3l** [comment]
Hm, why do
- `scraping_filter`
- `scraping`
- `qed_breit_wheeler_2d_opmd`
- `qed_breit_wheeler_3d_opmd`

fail now...

**Comment by guj** [comment]
Just checked,  the input file in issue 4604 works!

**Comment by guj** [comment]
I noticed orders of inputs are shuffled in several functions. Why is that?

**Comment by ax3l** [comment]
> I noticed orders of inputs are shuffled in several functions. Why is that?

I pass the offsets as references now, thus I cannot use default parameters anymore.

**Comment by guj** [comment]
> > I noticed orders of inputs are shuffled in several functions. Why is that?
> 
> I pass the offsets as references now, thus I cannot use default parameters anymore.

Yes, I saw that. But orders of inputs are different.   For example totalParticlesFlushedAlready was placed a few lines up in FlushFormat.H.  Just curious.

**Comment by ax3l** [comment]
Simplified it further to get rid of state that we will forget during checkpoint-restart :) Too much back and forth over the frontend-backend APIs.

File: Source/Diagnostics/BTDiagnostics.cpp [hunk 2]
```diff
@@ -1271,10 +1269,10 @@ void BTDiagnostics::MergeBuffersForPlotfile (int i_snapshot)
                 InterleaveSpeciesHeader(recent_species_Header,snapshot_species_Header,
                                         m_output_species_names[i], m_buffer_flush_counter[i_snapshot]);
                 if (BufferSpeciesHeader.m_total_particles == 0) { continue; }
-                if (m_totalParticles_flushed_already[i_snapshot][i]==0) {
-                WARPX_ALWAYS_ASSERT_WITH_MESSAGE(
-                    std::rename(recent_ParticleHdrFilename.c_str(), snapshot_ParticleHdrFilename.c_str()) == 0,
-                    std::string("Renaming ").append(recent_ParticleHdrFilename).append(" to ").append(snapshot_ParticleHdrFilename).append(" has failed"));
+                if (!amrex::FileExists(snapshot_ParticleHdrFilename)) {
```
Comment (ax3l) [inline Source/Diagnostics/BTDiagnostics.cpp:1272]: @RevathiJambunathan @atmyers highlighting this: I want to remove `m_totalParticles_flushed_already` because it is brittle state.

Let me know if you would add another check for this line.

Comment (RevathiJambunathan) [reply Source/Diagnostics/BTDiagnostics.cpp:1272]: I think this is good!

File: Source/Diagnostics/BTDiagnostics.H (hunk 1 above)
Comment (RevathiJambunathan) [reply Source/Diagnostics/BTDiagnostics.H:403]: is this also done for plotfile?

Comment (RevathiJambunathan) [reply Source/Diagnostics/BTDiagnostics.H:403]: ah I see - its not needed for plotfile - because we just merge headers and interleave data . this was needed mainly for openpmd. 
all good!

**Review by RevathiJambunathan — APPROVED** [review]

**Comment by RevathiJambunathan** [comment]
Looks good to me! @ax3l :) Thanks for this PR

**Review by RemiLehe — APPROVED** [review]
