### PR TITLE
Fix checkpoint with runtime components through the Python interface.

### LINKED ISSUE #2295: Checkpoints for restarting don't handle runtime attributes
Restarting from a checkpoint with python picmi works correctly as expected, however errors out when trying to restart from a checkpoint created from a simulation that added new runtime attributes (Warp: "pids").

Checkpoints are saved regardless, but may not be saving the new pids in the ParticleContainer.  When re-running the simulation from a checkpoint, the error given is "ParticleContainer::Restart(): nr != NStructReal + NumRealComps()" from AMReX_ParticleIO.H.  In addition, if a simulation without added PIDs is restarted from a checkpoint, then a new PID is added the simulation segfaults when outputting diagnostic information.

 The errors can be reproduced from using the following script modified from the WarpX tests
[PICMI_inputs_2d.txt](https://github.com/ECP-WarpX/WarpX/files/7140214/PICMI_inputs_2d.txt)

### PR DESCRIPTION
**Pull request by atmyers**
Fix #2295.

Specifically, this makes three changes:
1. It adds the particle component names to the Checkpoint files
2. If a Checkpoint file contains a runtime component that has not yet been added, it will be added on the fly.
3. If a runtime component has already been added, subsequent calls not not add it again.

### CODE REVIEW

**Comment by ax3l** [comment]
Let's rebase this one after #2335 / #2341 are merged, which add more restart safeguards

File: Source/Diagnostics/ParticleIO.cpp [hunk 1]
```diff
@@ -103,7 +105,84 @@ void
...
 {
     for (unsigned i = 0, n = species_names.size(); i < n; ++i) {
-        allcontainers[i]->Restart(dir, species_names[i]);
+        WarpXParticleContainer* pc = allcontainers[i].get();
+        std::string header_fn = dir + "/" + species_names[i] + "/Header";
+
+        Vector<char> fileCharPtr;
+        ParallelDescriptor::ReadAndBcastFile(header_fn, fileCharPtr);
+        std::string fileCharPtrString(fileCharPtr.dataPtr());
+        std::istringstream is(fileCharPtrString, std::istringstream::in);
```
Comment (ax3l) [inline Source/Diagnostics/ParticleIO.cpp:134]: Avoiding silent read corruptions:
```suggestion
        std::istringstream is(fileCharPtrString, std::istringstream::in);
        is.exceptions(std::ios_base::failbit | std::ios_base::badbit);
```

**Comment by EtherealMC-Bit** [comment]
The script in the original [issue](https://github.com/ECP-WarpX/WarpX/issues/2295) now verifies that the runtime attributes were added correctly, so it looks like this fixes it!

**Comment by ax3l** [comment]
@atmyers ready for rebase :)

File: Source/Diagnostics/FlushFormats/FlushFormatCheckpoint.cpp [hunk 2]
```diff
@@ -159,8 +159,35 @@ FlushFormatCheckpoint::CheckpointParticles (
     const amrex::Vector<ParticleDiag>& particle_diags) const
 {
     for (unsigned i = 0, n = particle_diags.size(); i < n; ++i) {
```
Comment (ax3l) [inline Source/Diagnostics/FlushFormats/FlushFormatCheckpoint.cpp:161]: In this function and potentially after this look, we probably also need to treat the laser particles to write our their positions

cc @RemiLehe

File: Source/Diagnostics/ParticleIO.cpp [hunk 3]
```diff
@@ -107,7 +109,85 @@ MultiParticleContainer::Restart (const std::string& dir)
     // - laser_names
     // we don't need to read back the laser particle charge/mass
     for (unsigned i = 0, n = species_names.size(); i < n; ++i) {
```
Comment (ax3l) [inline Source/Diagnostics/ParticleIO.cpp:127]: After this function in a separate look, we should read back the laser particle positions.

They are stored in the 2nd part of `allcontainers`

**Comment by ax3l** [comment]
The current implementation looks good to me. Can we design or repurpose an existing test to cover this permanently? :)
cc @MKieburtz

**Comment by EtherealMC-Bit** [comment]
I'm not sure about an existing test, although the script in #2295 is a nice and clean way of demonstrating that this works correctly.

**Comment by ax3l** [comment]
LGTM, it's short and small. let's add this one? :)

File: Source/Diagnostics/FlushFormats/FlushFormatCheckpoint.cpp (hunk 2 above)
Comment (atmyers) [reply Source/Diagnostics/FlushFormats/FlushFormatCheckpoint.cpp:161]: Support for this is added in PR #2360 - I recommend we merge that PR first, then rebase this one.

**Comment by ax3l** [comment]
@atmyers thank you for #2360 - do you like to rebase the PR here now? :)

**Comment by atmyers** [comment]
I have now added a CI test for this, based on the original script from modern electron.

File: Python/pywarpx/picmi.py [hunk 4]
```diff
@@ -1085,6 +1086,10 @@ def initialize_inputs(self):
         self.diagnostic.diag_type = 'Full'
         self.diagnostic.format = 'checkpoint'
 
+        if self.write_dir is not None or self.file_prefix is not None:
```
Comment (atmyers) [inline Python/pywarpx/picmi.py:1089]: I needed to modify the Python interface a bit here so that Checkpoint files could be configured to use a custom file prefix, as needed by the regression testing suite. Maybe @dpgrote could weigh in on whether this is the right way to fix this? 

I could also split this into a separate PR, if needed.

Comment (ax3l) [reply Python/pywarpx/picmi.py:1089]: LGTM. I think you can even remove the `if` line here with the logic in the next two lines

Let's also add an inline comment to document the need for this modification, otherwise this convention looks a bit magical to future readers

File: Python/pywarpx/picmi.py [hunk 5]
```diff
@@ -1085,6 +1086,10 @@ def initialize_inputs(self):
...
+            write_dir = (self.write_dir or 'diags')
+            file_prefix = (self.file_prefix or self.name)
+            self.diagnostic.file_prefix = write_dir + '/' + file_prefix
```
Comment (ax3l) [inline Python/pywarpx/picmi.py:1092]:
```suggestion
        # use checkpoint naming scheme expected by WarpX regression test suite
        write_dir = (self.write_dir or 'diags')
        file_prefix = (self.file_prefix or self.name)
        self.diagnostic.file_prefix = write_dir + '/' + file_prefix
```

File: Source/Diagnostics/FlushFormats/FlushFormatCheckpoint.cpp [hunk 6]
```diff
@@ -159,8 +159,35 @@ FlushFormatCheckpoint::CheckpointParticles (
...
+        real_names.push_back("weight");
+
+        real_names.push_back("momentum_x");
+        real_names.push_back("momentum_y");
+        real_names.push_back("momentum_z");
+
+#ifdef WARPX_DIM_RZ
+        real_names.push_back("theta");
+#endif
+
```
Comment (ax3l) [inline Source/Diagnostics/FlushFormats/FlushFormatCheckpoint.cpp:178]: Do we need:
- ionization state
- optical depth / QED params

here as well? Just double-checking, I think they are in `auto const& x : runtime_rnames` below, aren't they?

Comment (atmyers) [reply Source/Diagnostics/FlushFormats/FlushFormatCheckpoint.cpp:178]: Yes, they are handled below. Only the compile-time ones need to be handled here.

**Review by ax3l — APPROVED** [review]
Thanks a lot for this, that's great!
The patch & test looks generally good to me.

Comment on the Python side and just double-checking the extra SoA attributes for ionization/QED are there.

File: Python/pywarpx/picmi.py (hunk 5 above)
Comment (atmyers) [reply Python/pywarpx/picmi.py:1092]: It's not really specific to the test suite - the other diagnostic types FieldDiagnostic and ParticleDiagnostic already let you pass in a custom file prefix for whatever reason you want, as you can in the C++ interface. This just makes the Checkpoints behave the same way.  This `if` block is basically just copied from there.

Comment (dpgrote) [reply Python/pywarpx/picmi.py:1092]: Yes, this looks good. My preference is to keep the `if` check - this is a subtle difference but with the `if`, `diagnostic.file_prefix` won't be set if `write_dir` and `file_prefix` are not set and so it will rely on its default value in the C++ (this avoids having a default value defined in two different places).

I just noticed this - it should be `self.diagnostic.file_prefix = os.path.join(write_dir, file_prefix)` to be proper Python.

Comment (atmyers) [reply Python/pywarpx/picmi.py:1092]: Sounds good - I'll issue a follow-up PR to change the ` + '/' + `, I think the modern electron folks are waiting on this one to be merged.
