### PR TITLE
MergeBuffersForPlotfile: Barrier

### LINKED ISSUE #2382: cartesian3d: BTD_ReducedSliceDiag Test Unstable
In CI, we see that the `cartesian3d` test `BTD_ReducedSliceDiag` sporatically crashes.
This needs maybe a build in debug mode locally to find out where it crashes.

CC @RemiLehe @RevathiJambunathan

### PR DESCRIPTION
**Pull request by ax3l**
Make sure that all MPI ranks are in sync, i.e., have closed the files that they wrote, before trying to merge them.

Fix #2382

### CODE REVIEW

File: Source/Diagnostics/BTDiagnostics.cpp [hunk 1]
```diff
@@ -662,6 +662,12 @@ void BTDiagnostics::TMP_ClearSpeciesDataForBTD ()
 
 void BTDiagnostics::MergeBuffersForPlotfile (int i_snapshot)
 {
+    // Make sure all MPI ranks wrote their files and closed it
+    // Note: additionally, since a Barrier does not guarantee a FS sync
+    //       on a parallel FS, we might need to add timeouts and re-tries
+    //       to the open calls below when running at scale.
+    amrex::ParallelDescriptor::Barrier();
```
Comment (ax3l) [inline Source/Diagnostics/BTDiagnostics.cpp:669]: @RevathiJambunathan are we guaranteeing that all MPI ranks reach this point? :)
Otherwise we could call a barrier on a sub-communicator, if needed.

Comment (RevathiJambunathan) [reply Source/Diagnostics/BTDiagnostics.cpp:669]: All the I/O for BTD is done within `amrex:ParallelContext::IOProcessorSub()` for the cases when we have only some processors dedicated to I/O

Comment (atmyers) [reply Source/Diagnostics/BTDiagnostics.cpp:669]: There is also `amrex::ParallelContext::BarrierSub()` for that.

Comment (ax3l) [reply Source/Diagnostics/BTDiagnostics.cpp:669]: Ok, cool!
So that means the current PR proposal should work (sync all that potentially wrote a plotfile).

Btw, is there a specific reason for the barrier at the end of `BTDiagnostics::MergeBuffersForPlotfile`?

**Review by RevathiJambunathan — APPROVED** [review]
Thank you Axel for this PR!
