### PR TITLE
Fix conditionless `ComputeSpaceChargeField` 

### LINKED ISSUE #6497: Hybrid Ohm Solver: artifacts near tilted EBs
## Description

When running WarpX Hybrid-PIC simulations with embedded boundaries (EBs) that are tilted (not aligned with grid axes), strong artifacts appear in the E and B fields starting at timestep 1. These artifacts seem to stem from spurious displacement currents (`j_displacement`) near the boundaries.

### Conditions for artifacts to appear:
1. ✅ Embedded boundary is tilted (not aligned with grid axes)
2. ✅ External B-field is present (`sim.add_applied_field`)
3. ✅ EB potential is set (non-zero)
4. ❌ Does NOT occur on boundaries that are aligned with axes

### Observable behavior:
- Fields are clean at step 0
- Strong artifacts appear in `j_displacement` at step 1
- These artifacts dominate E and B fields near boundaries
- Artifacts eventually vanish after many timesteps (but meanwhile, physics are corrupted)

Image

Image

Image

## Minimal Reproducer

A minimal test case is attached in `minimal_tilted_boundary.py`. It demonstrates:
- One tilted boundary (45°) + one aligned boundary
- Circular plasma profile that does not touch any boundaries in the beginning
- `holmstrom_vacuum_region=True` to deal with vacuum regions
- Smooth density tapering (5 cells gradient) to vacuum
- Plasma current in y-direction (out-of-plane)
- External B-field in x-direction
- All boundaries: Dirichlet (fields) / Absorbing (particles)

### Files

Requires an installation of the `development` branch with Python bindings 

* [hybrid_pic_helpers.py](https://github.com/user-attachments/files/24650018/hybrid_pic_helpers.py)
* [minimal_tilted_boundary.py](https://github.com/user-attachments/files/24650525/minimal_tilted_boundary.py)
* [run_warpx.sh](https://github.com/user-attachments/files/24650363/run_warpx.sh)

## System information

Please check all relevant boxes and provide details.

- Operating system (name and version):
  - [x] Linux: on Perlmutter at NERSC
  - [ ] macOS: e.g., macOS Monterey 12.4
  - [ ] Windows: e.g., Windows 11 Pro
- Version of WarpX `25.10-125-ge192e42aa09e` with AMReX `25.11-47-gc4fcda1fb2ea`
- Installation method:
  - [ ] Conda
  - [ ] Spack
  - [ ] PyPI
  - [ ] Brew
  - [x] From source with CMake
  - [x] Module system on an HPC cluster
- Other dependencies: yes/no, describe
- Computational resources:
  - [x] MPI: 1 MPI rank
  - [ ] OpenMP: e.g., 2 OpenMP threads
  - [x] CPU: 1 Perlmutter node
  - [x] GPU: 1 GPU

## Additional information

* Removing external B-field → artifacts change
* Removing EB potential → artifacts change
* Removing both → artifacts vanish (confirms the interaction)

### Hypothesis
- The plasma current is computed as J_plasma = curl(B) / μ₀
- Finite-difference stencils (`DownwardDx`, `DownwardDy`, `DownwardDz`) reach across embedded boundaries into covered cells when boundaries are tilted
- This produces spurious currents near boundaries
- These get amplified by the (J - Ji) × B term in Ohm's law when an external B-field is present
- Result: large spurious E-fields that dominate the solution

### PR DESCRIPTION
**Pull request by aeriforme**
Adds a conditional check to only call `ComputeSpaceChargeField` when an electrostatic solver is enabled or when using hybrid-PIC, matching the logic in `WarpXEvolve.cpp`.

With the help of the robots, I have to check if it's correct.

### CODE REVIEW

**Comment by roelof-groenewald** [comment]
I realize this is still marked as WIP; just wanted to point out that I think a similar fix is needed for #6497.

File: Source/Initialization/WarpXInitData.cpp [hunk 1]
```diff
@@ -878,17 +878,26 @@ WarpX::InitData ()
...
+                bool const reset_fields = false; // Do not erase previous user-specified values on the grid
+                ComputeSpaceChargeField(reset_fields);
+                if (electrostatic_solver_id == ElectrostaticSolverAlgo::LabFrameElectroMagnetostatic) {
+                    ComputeMagnetostaticField();
+                }
+                // Add external fields to the fine patch fields. This makes it so that the
+                // net fields are the sum of the field solutions and any external fields.
+                for (int lev = 0; lev <= max_level; ++lev) {
+                    AddExternalFields(lev);
+                }
```
Comment (roelof-groenewald) [inline Source/Initialization/WarpXInitData.cpp]: This will still need to be done regardless of the solver since this is where the "initial" fields are set.

File: Source/Initialization/WarpXInitData.cpp [hunk 2]
```diff
@@ -878,12 +878,27 @@ WarpX::InitData ()
...
+        // any species has initialize_self_fields = true, or when boundary potential is specified
+        bool has_initialize_self_fields = false;
+        for (auto const& species : *mypc) {
+            has_initialize_self_fields |= species->initialize_self_fields;
+        }
+        bool has_boundary_potential = m_electrostatic_solver->m_poisson_boundary_handler->m_boundary_potential_specified;
+        if( electrostatic_solver_id != ElectrostaticSolverAlgo::None ||
+            WarpX::electromagnetic_solver_id == ElectromagneticSolverAlgo::HybridPIC ||
+            has_initialize_self_fields ||
+            has_boundary_potential )
```
Comment (roelof-groenewald) [inline Source/Initialization/WarpXInitData.cpp]: This `if` block only serves to not execute the `beforeInitESolve` and `afterInitESolve` callbacks when this condition does is not satisfied. Why do that? Is there a downside to still allowing those callbacks even if the initial field solve does not actually occur?

File: Source/Initialization/WarpXInitData.cpp [hunk 3]
```diff
@@ -878,12 +878,27 @@ WarpX::InitData ()
...
+            ExecutePythonCallback("beforeInitEsolve");
+            if (electrostatic_solver_id != ElectrostaticSolverAlgo::None || has_initialize_self_fields || has_boundary_potential) {
+                bool const reset_fields = false; // Do not erase previous user-specified values on the grid
+                ComputeSpaceChargeField(reset_fields);
+                if (electrostatic_solver_id == ElectrostaticSolverAlgo::LabFrameElectroMagnetostatic) {
+                    ComputeMagnetostaticField();
+                }
+            }
+            ExecutePythonCallback("afterInitEsolve");
         }
```
Comment (roelof-groenewald) [inline Source/Initialization/WarpXInitData.cpp]: Just to be explicit, my suggestion with the above comment would be to do the following:
```suggestion
        ExecutePythonCallback("beforeInitEsolve");
        if (electrostatic_solver_id != ElectrostaticSolverAlgo::None || has_initialize_self_fields || has_boundary_potential) {
            bool const reset_fields = false; // Do not erase previous user-specified values on the grid
            ComputeSpaceChargeField(reset_fields);
            if (electrostatic_solver_id == ElectrostaticSolverAlgo::LabFrameElectroMagnetostatic) {
                ComputeMagnetostaticField();
            }
        }
        ExecutePythonCallback("afterInitEsolve");
```

File: Source/Initialization/WarpXInitData.cpp [hunk 4]
```diff
@@ -877,14 +877,27 @@ WarpX::InitData ()
...
+        // any species has initialize_self_fields = true, or when boundary potential is specified
+        bool has_initialize_self_fields = false;
+        for (auto const& species : *mypc) {
+            has_initialize_self_fields |= species->initialize_self_fields;
         }
+        bool has_boundary_potential = m_electrostatic_solver->m_poisson_boundary_handler->m_boundary_potential_specified;
+        if( electrostatic_solver_id != ElectrostaticSolverAlgo::None ||
+            WarpX::electromagnetic_solver_id == ElectromagneticSolverAlgo::HybridPIC ||
+            has_initialize_self_fields ||
+            has_boundary_potential )
```
Comment (roelof-groenewald) [inline Source/Initialization/WarpXInitData.cpp]: This change is needed to fix #6497:
```suggestion
        if( (electrostatic_solver_id != ElectrostaticSolverAlgo::None ||
             has_initialize_self_fields ||
             has_boundary_potential) 
            && WarpX::electromagnetic_solver_id != ElectromagneticSolverAlgo::HybridPIC)
```

File: Source/Initialization/WarpXInitData.cpp [hunk 5]
```diff
@@ -877,14 +877,27 @@ WarpX::InitData ()
...
     {
-        // Loop through species and calculate their space-charge field
-        bool const reset_fields = false; // Do not erase previous user-specified values on the grid
         ExecutePythonCallback("beforeInitEsolve");
-        ComputeSpaceChargeField(reset_fields);
-        ExecutePythonCallback("afterInitEsolve");
-        if (electrostatic_solver_id == ElectrostaticSolverAlgo::LabFrameElectroMagnetostatic) {
-            ComputeMagnetostaticField();
+        // Loop through species and calculate their space-charge field
+        // Field solve step for electrostatic or hybrid-PIC solvers, or when
```
Comment (roelof-groenewald) [inline Source/Initialization/WarpXInitData.cpp]:
```suggestion
        // Field solve step for electrostatic solvers, or when
```

File: Source/Initialization/WarpXInitData.cpp (hunk 4 above)
Comment (aeriforme) [reply Source/Initialization/WarpXInitData.cpp]: Ah so you do NOT want to do space charge with the hybrid solver?

Comment (roelof-groenewald) [reply Source/Initialization/WarpXInitData.cpp]: Yes, exactly :)

Comment (aeriforme) [reply Source/Initialization/WarpXInitData.cpp]: Doh - I completely misunderstood, sorry

Comment (roelof-groenewald) [reply Source/Initialization/WarpXInitData.cpp]: No worries. I still don't actually understand why it matters, but since it taking it away doesn't break anything AND does fix a known problem we can merge this and I'll figure out why it makes a difference later haha

**Review by roelof-groenewald — APPROVED** [review]
