### PR TITLE
#2534: Don't access position vector values beyond the configured dimension

### LINKED ISSUE #2534: CUDA memory errors in scrapeParticles
Running `development 13f6e984` under Nvidia's `compute-sanitizer`, and input from `Examples/Physics_applications/capacitive_discharge/inputs_2d`, I see the following errors reported:

> `compute-sanitizer ~/build/2021-11-05-GPU/bin/warpx inputs_2d`

```
========= Invalid __global__ read of size 4 bytes
=========     at 0x790 in /home/ubuntu/build/2021-11-05-GPU/_deps/fetchedamrex-src/Src/Base/AMReX_GpuLaunchFunctsG.H:899:_ZZN5amrex14ParallelForRNGIiZ15scrapeParticlesI22WarpXParticleContainerN23ParticleBoundaryProcess6AbsorbELi0EEvRT_RKNS_6VectorIPKNS_8MultiFabESaISA_EEEiiOT0_EUliRKNS_12RandomEngineEE_vEENSt9enable_ifIXsr5amrex19MaybeDeviceRunnableISF_vEE5valueEvE4typeES5_SG_ENKUlvE_clEv
=========     by thread (95,0,0) in block (17,0,0)
=========     Address 0x75cea828bfdc14fa is misaligned
=========     Device Frame:/home/ubuntu/build/2021-11-05-GPU/_deps/fetchedamrex-src/Src/Base/AMReX_GpuLaunchGlobal.H:16:_ZN5amrex13launch_globalILi256EZNS_14ParallelForRNGIiZ15scrapeParticlesI22WarpXParticleContainerN23ParticleBoundaryProcess6AbsorbELi0EEvRT_RKNS_6VectorIPKNS_8MultiFabESaISB_EEEiiOT0_EUliRKNS_12RandomEngineEE_vEENSt9enable_ifIXsr5amrex19MaybeDeviceRunnableISG_vEE5valueEvE4typeES6_SH_EUlvE_EEvSG_ [0xad0]
=========     Saved host backtrace up to driver entry point at kernel launch time
=========     Host Frame: [0x25428a]
=========                in /lib/x86_64-linux-gnu/libcuda.so.1
=========     Host Frame: [0x78e0fb]
=========                in /home/ubuntu/build/2021-11-05-GPU/bin/warpx
=========     Host Frame: [0x7e1820]
=========                in /home/ubuntu/build/2021-11-05-GPU/bin/warpx
=========     Host Frame: [0x350e8d]
=========                in /home/ubuntu/build/2021-11-05-GPU/bin/warpx
=========     Host Frame: [0x3525c9]
=========                in /home/ubuntu/build/2021-11-05-GPU/bin/warpx
=========     Host Frame: [0x35380a]
=========                in /home/ubuntu/build/2021-11-05-GPU/bin/warpx
=========     Host Frame: [0x344b46]
=========                in /home/ubuntu/build/2021-11-05-GPU/bin/warpx
=========     Host Frame: [0x291a3d]
=========                in /home/ubuntu/build/2021-11-05-GPU/bin/warpx
=========     Host Frame: [0xa8c94]
=========                in /home/ubuntu/build/2021-11-05-GPU/bin/warpx
=========     Host Frame:__libc_start_main [0x270b3]
=========                in /lib/x86_64-linux-gnu/libc.so.6
=========     Host Frame: [0xbfe2e]
=========                in /home/ubuntu/build/2021-11-05-GPU/bin/warpx
========= 
========= Invalid __global__ read of size 4 bytes
=========     at 0x790 in /home/ubuntu/build/2021-11-05-GPU/_deps/fetchedamrex-src/Src/Base/AMReX_GpuLaunchFunctsG.H:899:_ZZN5amrex14ParallelForRNGIiZ15scrapeParticlesI22WarpXParticleContainerN23ParticleBoundaryProcess6AbsorbELi0EEvRT_RKNS_6VectorIPKNS_8MultiFabESaISA_EEEiiOT0_EUliRKNS_12RandomEngineEE_vEENSt9enable_ifIXsr5amrex19MaybeDeviceRunnableISF_vEE5valueEvE4typeES5_SG_ENKUlvE_clEv
=========     by thread (32,0,0) in block (337,0,0)
=========     Address 0xb3dbc5afc001120c is out of bounds
=========     Device Frame:/home/ubuntu/build/2021-11-05-GPU/_deps/fetchedamrex-src/Src/Base/AMReX_GpuLaunchGlobal.H:16:_ZN5amrex13launch_globalILi256EZNS_14ParallelForRNGIiZ15scrapeParticlesI22WarpXParticleContainerN23ParticleBoundaryProcess6AbsorbELi0EEvRT_RKNS_6VectorIPKNS_8MultiFabESaISB_EEEiiOT0_EUliRKNS_12RandomEngineEE_vEENSt9enable_ifIXsr5amrex19MaybeDeviceRunnableISG_vEE5valueEvE4typeES6_SH_EUlvE_EEvSG_ [0xad0]
=========     Saved host backtrace up to driver entry point at kernel launch time
=========     Host Frame: [0x25428a]
=========                in /lib/x86_64-linux-gnu/libcuda.so.1
=========     Host Frame: [0x78e0fb]
=========                in /home/ubuntu/build/2021-11-05-GPU/bin/warpx
=========     Host Frame: [0x7e1820]
=========                in /home/ubuntu/build/2021-11-05-GPU/bin/warpx
=========     Host Frame: [0x350e8d]
=========                in /home/ubuntu/build/2021-11-05-GPU/bin/warpx
=========     Host Frame: [0x3525c9]
=========                in /home/ubuntu/build/2021-11-05-GPU/bin/warpx
=========     Host Frame: [0x35380a]
=========                in /home/ubuntu/build/2021-11-05-GPU/bin/warpx
=========     Host Frame: [0x344b46]
=========                in /home/ubuntu/build/2021-11-05-GPU/bin/warpx
=========     Host Frame: [0x291a3d]
=========                in /home/ubuntu/build/2021-11-05-GPU/bin/warpx
=========     Host Frame: [0xa8c94]
=========                in /home/ubuntu/build/2021-11-05-GPU/bin/warpx
=========     Host Frame:__libc_start_main [0x270b3]
=========                in /lib/x86_64-linux-gnu/libc.so.6
=========     Host Frame: [0xbfe2e]
=========                in /home/ubuntu/build/2021-11-05-GPU/bin/warpx
```

### PR DESCRIPTION
**Pull request by PhilMiller**
Fixes #2534

### CODE REVIEW

File: Source/EmbeddedBoundary/ParticleScraper.H [hunk 1]
```diff
@@ -172,10 +172,14 @@ scrapeParticles (PC& pc, const amrex::Vector<const amrex::MultiFab*>& distance_t
...
                 amrex::RealVect pos;
+#if (defined WARPX_DIM_3D)
                 pos[0] = xp - normal[0]*phi_value;
                 pos[1] = yp - normal[1]*phi_value;
                 pos[2] = zp - normal[2]*phi_value;
-
+#elif (defined WARPX_DIM_XZ)
+                pos[0] = xp - normal[0]*phi_value;
+                pos[1] = yp - normal[1]*phi_value;
+#endif
```
Comment (ax3l) [inline Source/EmbeddedBoundary/ParticleScraper.H:189]: @dpgrote do you see on first view what the corresponding RZ logic would be? :)
Let's fix all three (four #2307) geometries at once.

This is the 1D3V logic and I think for 2D3V you need to replace `yp` with `zp` in the current PR:
```suggestion
#elif (defined WARPX_DIM_XZ)
                pos[0] = xp - normal[0]*phi_value;
                pos[1] = zp - normal[1]*phi_value;
#elif defined(WARPX_DIM_1D_Z)
                pos[0] = zp - normal[0]*phi_value;
#endif
```

File: Source/EmbeddedBoundary/ParticleScraper.H [hunk 2]
```diff
@@ -172,10 +172,14 @@ scrapeParticles (PC& pc, const amrex::Vector<const amrex::MultiFab*>& distance_t
...
                 DistanceToEB::normalize(normal);
 
                 if (phi_value < 0.0) {
```
Comment (PhilMiller) [inline Source/EmbeddedBoundary/ParticleScraper.H]: While we're at it, should we move all the calculation inside this `if`?

Comment (ax3l) [reply Source/EmbeddedBoundary/ParticleScraper.H]: Good idea :)

File: Source/EmbeddedBoundary/ParticleScraper.H (hunk 1 above)
Comment (dpgrote) [reply Source/EmbeddedBoundary/ParticleScraper.H:189]: In RZ, this would need to use the raw data (from the AOS) since this would need the `r` and `z` values, since the boundaries would presumably be defined in `r,z`.

Comment (PhilMiller) [reply Source/EmbeddedBoundary/ParticleScraper.H:189]: @ax3l I fixed the `yp/zp` mixup.

@dpgrote I'll be happy to add the `RZ` case if I know what it needs to say, or directly accept a 'suggestion' here on the PR

Comment (PhilMiller) [reply Source/EmbeddedBoundary/ParticleScraper.H:189]: Does the code even support EB in RZ configurations right now?

Comment (ax3l) [reply Source/EmbeddedBoundary/ParticleScraper.H:189]: Good question. If not, let's add an assert here that the person that adds it will find the to-be-updated location via an assert instead of a segfault :D

**Review by atmyers — APPROVED** [review]

**Comment by atmyers** [comment]
Thanks for fixing!

File: Source/EmbeddedBoundary/ParticleScraper.H (hunk 1 above)
Comment (PhilMiller) [reply Source/EmbeddedBoundary/ParticleScraper.H:189]: Aborts in the RZ case for now. Someone can address that later if it comes up.

File: Source/EmbeddedBoundary/ParticleScraper.H [hunk 3]
```diff
@@ -168,17 +168,27 @@ scrapeParticles (PC& pc, const amrex::Vector<const amrex::MultiFab*>& distance_t
...
+                    pos[0] = xp - normal[0]*phi_value;
+                    pos[1] = yp - normal[1]*phi_value;
+                    pos[2] = zp - normal[2]*phi_value;
+#elif (defined WARPX_DIM_XZ)
+                    pos[0] = xp - normal[0]*phi_value;
+                    pos[1] = zp - normal[1]*phi_value;
+#elif (defined WARPX_DIM_1D_Z)
+                    pos[0] = zp - normal[0]*phi_value;
+#elif (defined WARPX_DIM_RZ)
+                    amrex::Abort("Scraping from an EB is not supported in RZ");
```
Comment (dpgrote) [inline Source/EmbeddedBoundary/ParticleScraper.H:188]: This would work if you called `getPosition.AsStored(ip, xp, yp, zp);` above at line 164. With that call, the `xp` will be the radius and `yp` the theta. Then you would use the same lines as above for `WARPX_DIM_XZ`. This is of course assuming that the `phi_value` and `normal` will be calculated correctly for RZ.

Comment (ax3l) [reply Source/EmbeddedBoundary/ParticleScraper.H:188]: I'll merge the fix for now to avoid further collisions with #2401.
Follow-ups welcome :)

**Review by ax3l — APPROVED** [review]
Thanks a lot!
