### PR TITLE
Bug fixes and cleanup in load balancing

### LINKED ISSUE #2554: Load balance high residual and seg fault with EB
When trying to use load balancing with the input file from https://github.com/ECP-WarpX/WarpX/pull/2538, with the changes from https://github.com/ECP-WarpX/WarpX/pull/2401, and adding return statements to the beginning of `WarpX::ComputeEdgeLengths`, `WarpX::ComputeFaceAreas`, `WarpX::ScaleEdges`, and `WarpX::ScaleAreas`, we get a very high residual (3e289) on step 4 (load_balance_intervals = 5), causing the run to fail and exit. If we set a high absolute tolerance for the MLMG solver (3e290) to bypass this high residual, the program will segfault at the beginning of step 5 with backtraces from some of the processes.

The input file we used is [inputs2d.txt](https://github.com/ECP-WarpX/WarpX/files/7529917/inputs2d.txt).

This is one backtrace file we got using a debug build, when running with the conditions above to reach the segfault on step 5. This simulation was run with 8 mpi cores and 1 omp thread. [Backtrace.0.0.txt](https://github.com/ECP-WarpX/WarpX/files/7529925/Backtrace.0.0.txt)

### PR DESCRIPTION
**Pull request by roelof-groenewald**
There are 5 changes made in this PR:
1. added rebuilding of EB multifabs to `WarpX::RemakeLevel()` - bug fix
2. added a helper function to remake `MultiFab`s and `iMultiFab`s to reduce duplicate code - clean-up
3. added a `redistribute` function to `ParticleBoundaryBuffer` that is called from `WarpX::LoadBalance` to enable current tracking while using load balancing - bug fix
4. consistently use `DistributionMap` rather than `dmap` in ElectrostaticSolver.cpp - I don't think this actually makes a difference but is probably worth it for the sake of consistency.
5. added a helper function `InitializeEBGridData()` to set up all the grid data quantities used with EBs that is called from both `WarpX::InitLevelData` and `WarpX::RemakeLevel` - clean-up

As far as I can tell these changes fixes all the issues discussed in #2554 (therefore fixes #2554).

Note that there are still a number of `MultiFab`s declared in `WarpX.H` that is not rebuilt during load balancing. These include `ECTRhofield`, `F_slice`, `G_slice`, `rho_slice`, `current_slice`, `Efield_slice` and `Bfield_slice`. I don't see those used anywhere in the code though.

### CODE REVIEW

File: Source/WarpX.H [hunk 1]
```diff
@@ -819,6 +819,12 @@ protected:
     //! data.  Called by AmrCore::regrid.
     virtual void RemakeLevel (int lev, amrex::Real time, const amrex::BoxArray& ba,
                               const amrex::DistributionMapping& dm) final;
+    virtual void RemakeMultiFab (std::unique_ptr<amrex::MultiFab>& mf,
+                                 const amrex::DistributionMapping& dm,
+                                 const bool redistribute = true) final;
+    virtual void RemakeiMultiFab (std::unique_ptr<amrex::iMultiFab>& mf,
+                                 const amrex::DistributionMapping& dm,
+                                 const bool redistribute = true) final;
```
Comment (PhilMiller) [inline Source/WarpX.H]: A couple comments on these
* The only member variable I can see that they access is `ng`, so if that were passed as an argument, they could be  free functions (possibly `static`) in `WarpXRegrid.cpp`.
* There's no difference between the bodies of these two overloads. A single `template <typename MultiFabType> void RemakeMultiFab(std::unique_ptr<MultiFabType>& mf, ...)` would cover both.
* Just a general C++ note - it's rather silly to declare a member function `virtual ... final` all in one go. If it's the only possible implementation, it just shouldn't be `virtual`

File: Source/Parallelization/WarpXRegrid.cpp [hunk 2]
```diff
@@ -358,57 +282,14 @@ WarpX::RemakeLevel (int lev, Real /*time*/, const BoxArray& ba, const Distributi
...
-                                                                  dm, charge_buf[lev]->nComp(), ng);
-                // pmf->ParallelCopy(*charge_buf[lev][idim], 0, 0, charge_buf[lev]->nComp(), ng, ng);
-                charge_buf[lev] = std::move(pmf);
-            }
-            if (current_buffer_masks[lev])
-            {
-                const IntVect& ng = current_buffer_masks[lev]->nGrowVect();
-                auto pmf = std::make_unique<iMultiFab>(current_buffer_masks[lev]->boxArray(),
-                                                                    dm, current_buffer_masks[lev]->nComp(), ng);
-                // we can avoid this since we immediately re-build the values via BuildBufferMasks()
```
Comment (PhilMiller) [inline Source/Parallelization/WarpXRegrid.cpp:399]: Is it worth copying this comment over, and inserting 'redistributing' before 'this'?

**Comment by PhilMiller** [comment]
If the team is unconcerned about the style notes I made, I believe this is otherwise ready to be merged as is.

File: Source/WarpX.H (hunk 1 above)
Comment (roelof-groenewald) [reply Source/WarpX.H]: Thanks for the comments! On the first point: there are also calls to `mf->boxArray()` and `mf->nComp()` besides the `ng = mf->nGrowVect()` line, so I think it is best to keep the arguments to `RemakeMultiFab` as is. For the other comments I just added a commit with the suggested changes.

Comment (PhilMiller) [reply Source/WarpX.H]: Oops, sorry, I'm silly. I missed that `ng` is a local variable, not a member of `WarpX` at all.

If you move the template definition up above the call sites in the .cpp file, then it doesn't need to appear in the header at all. And of course, need not be a member of WarpX

Comment (roelof-groenewald) [reply Source/WarpX.H]: Good point, thanks!

File: Source/Parallelization/WarpXRegrid.cpp [hunk 3]
```diff
@@ -140,14 +144,51 @@ WarpX::LoadBalance ()
...
+            RemakeMultiFab(current_store[lev][idim], dm, false);
+
+#ifdef AMREX_USE_EB
+            RemakeMultiFab(Venl[lev][idim], dm, false);
+            RemakeMultiFab(m_edge_lengths[lev][idim], dm, false);
+            RemakeMultiFab(m_face_areas[lev][idim], dm, false);
+            RemakeMultiFab(m_flag_info_face[lev][idim], dm, false);
+            RemakeMultiFab(m_flag_ext_face[lev][idim], dm, false);
+            RemakeMultiFab(m_area_mod[lev][idim], dm, false);
+#endif
```
Comment (lgiacome) [inline Source/Parallelization/WarpXRegrid.cpp]: Since all these multifabs are only initialized with the Yee/CKC/ECT solvers with EB we can avoid remaking them in all the other cases.

```suggestion
#ifdef AMREX_USE_EB
            if (WarpX::maxwell_solver_id == MaxwellSolverAlgo::Yee || 
                WarpX::maxwell_solver_id == MaxwellSolverAlgo::ECT || 
                WarpX::maxwell_solver_id == MaxwellSolverAlgo::CKC){ 
                RemakeMultiFab(m_edge_lengths[lev][idim], dm, false);
                RemakeMultiFab(m_face_areas[lev][idim], dm, false);
                if(WarpX::maxwell_solver_id == MaxwellSolverAlgo::ECT){
                    RemakeMultiFab(Venl[lev][idim], dm, false);
                    RemakeMultiFab(m_flag_info_face[lev][idim], dm, false);
                    RemakeMultiFab(m_flag_ext_face[lev][idim], dm, false);
                    RemakeMultiFab(m_area_mod[lev][idim], dm, false);
                    RemakeMultiFab(ECTRhofield[lev][idim], dm, false);
                }
            }
#endif
```

**Review by lgiacome — CHANGES_REQUESTED** [review]
Hi @roelof-groenewald, thanks so much for taking care also of the EB data in this PR!
I added a minor comment regarding the EM solvers.

On the other hand, we need to rebuild `m_borrowing` as well. I'm not sure how easy this will be because it is not an array of multifab's as you pointed out correctly.

If it is complicated to redistribute m_borrow, for the data relative to the ECT solver we can just reinitialize all the data and simply call again `ComputeFaceExtensions()`. This will introduce new computations but should work easily.
@WeiqunZhang what do you think?

File: Source/Parallelization/WarpXRegrid.cpp (hunk 3 above)
Comment (roelof-groenewald) [reply Source/Parallelization/WarpXRegrid.cpp]: Thanks!

**Comment by WeiqunZhang** [comment]
It's probably easier to just recompute m_borrowing.

**Review by PhilMiller — APPROVED** [review]

**Comment by lgiacome** [comment]
Alright so we need some more changes. I can suggest them later.

**Comment by roelof-groenewald** [comment]
> Alright so we need some more changes. I can suggest them later.

@lgiacome Feel free to directly commit to this branch if you'd like (although that might not be possible with our repo settings, I'm not 100% sure).

**Comment by ax3l** [comment]
In doubt, you can do a PR to this branch (https://github.com/ModernElectron/WarpX/tree/rg/load_balancing_fixes)

**Comment by PhilMiller** [comment]
Could those further changes reasonably be part of a follow-up PR? It would be nice to move forward on this, and have the working code for EB in electrostatic integrated.

File: Source/Parallelization/WarpXRegrid.cpp [hunk 4]
```diff
@@ -140,14 +144,61 @@ WarpX::LoadBalance ()
...
+                RemakeMultiFab(m_face_areas[lev][idim], dm, false);
+                if(WarpX::maxwell_solver_id == MaxwellSolverAlgo::ECT){
+                    RemakeMultiFab(Venl[lev][idim], dm, false);
+                    RemakeMultiFab(m_flag_info_face[lev][idim], dm, false);
+                    RemakeMultiFab(m_flag_ext_face[lev][idim], dm, false);
+                    RemakeMultiFab(m_area_mod[lev][idim], dm, false);
+                    RemakeMultiFab(ECTRhofield[lev][idim], dm, false);
+                }
+
+                m_borrowing[lev][idim] = std::make_unique<amrex::LayoutData<FaceInfoBox>>(amrex::convert(ba, Bfield_fp[lev][idim]->ixType().toIntVect()), dm);
```
Comment (roelof-groenewald) [inline Source/Parallelization/WarpXRegrid.cpp]: @WeiqunZhang or @lgiacome could you guys please confirm that this is the correct way to "reset" `m_borrowing`?

Comment (roelof-groenewald) [reply Source/Parallelization/WarpXRegrid.cpp]: Also, should this go inside the `if (WarpX::maxwell_solver_id == MaxwellSolverAlgo::ECT)` block? Plus I still need to add the `ComputeFaceExtensions()` call, right?

Comment (lgiacome) [reply Source/Parallelization/WarpXRegrid.cpp]: Sorry, I said I would look into it but then I ran out of time...
So the reset looks fine to me.

After that outside the loop over idim you need to call first `MarkCells()` and after you call `ComputeFaceExtensions()`.

This has to happen only `if (WarpX::maxwell_solver_id == MaxwellSolverAlgo::ECT)`

I can add the suggestion so that you can just commit it.

Comment (roelof-groenewald) [reply Source/Parallelization/WarpXRegrid.cpp]: Sounds good. I'll wait for the suggestion. Thanks!

Comment (lgiacome) [inline Source/Parallelization/WarpXRegrid.cpp]:
```suggestion
                    RemakeMultiFab(ECTRhofield[lev][idim], dm, false);
                    m_borrowing[lev][idim] = std::make_unique<amrex::LayoutData<FaceInfoBox>>(amrex::convert(ba, Bfield_fp[lev][idim]->ixType().toIntVect()), dm);
                }
```

File: Source/Parallelization/WarpXRegrid.cpp [hunk 5]
```diff
@@ -140,14 +144,61 @@ WarpX::LoadBalance ()
...
+
+            }
+#endif
+        }
+
```
Comment (lgiacome) [inline Source/Parallelization/WarpXRegrid.cpp:190]:
```suggestion
        // Since we have reset m_borrow we need to recompute the extensions. 
        //To do so we need to recompute m_flag_ext_face since has been changed 
        // the last time ComputeFaceExtensions has been called. For this reason we 
        // call MarkCells before ComputeFaceExtensions
        if(WarpX::maxwell_solver_id == MaxwellSolverAlgo::ECT){
            MarkCells();
            ComputeFaceExtensions();
        }
```

Comment (roelof-groenewald) [reply Source/Parallelization/WarpXRegrid.cpp:190]: Should these calls go inside the `#ifdef AMREX_USE_EB` block a little further below?

File: Source/Parallelization/WarpXRegrid.cpp (hunk 4 above)
Comment (lgiacome) [reply Source/Parallelization/WarpXRegrid.cpp]: I should have added the suggestions. It should be correct, but it would be great if you could have a second look at the style 😅

File: Source/Parallelization/WarpXRegrid.cpp (hunk 5 above)
Comment (lgiacome) [reply Source/Parallelization/WarpXRegrid.cpp:190]: Yes, you are right

File: Source/Parallelization/WarpXRegrid.cpp (hunk 4 above)
Comment (roelof-groenewald) [reply Source/Parallelization/WarpXRegrid.cpp]: Thanks a lot! I think this PR should now be just about ready to go.

File: Source/Parallelization/WarpXRegrid.cpp [hunk 6]
```diff
@@ -156,67 +206,19 @@ WarpX::RemakeLevel (int lev, Real /*time*/, const BoxArray& ba, const Distributi
...
         ComputeDistanceToEB();
+
+        // Since we have reset m_borrowing we need to recompute the extensions.
+        // To do so we need to recompute m_flag_ext_face since it has been changed
+        // since the last time ComputeFaceExtensions has been called. For this reason
+        // we call MarkCells before ComputeFaceExtensions
+        if(WarpX::maxwell_solver_id == MaxwellSolverAlgo::ECT){
+            MarkCells();
+            ComputeFaceExtensions();
+        }
```
Comment (lgiacome) [inline Source/Parallelization/WarpXRegrid.cpp:217]: Sorry I had a closer look and there is something more we need to add, but that should be it. 

```suggestion
        // Since we have reset m_borrowing we need to recompute the extensions.
        // To do so we need to recompute m_flag_ext_face since it has been changed
        // since the last time ComputeFaceExtensions has been called. For this reason
        // we call MarkCells before ComputeFaceExtensions
        if(WarpX::maxwell_solver_id == MaxwellSolverAlgo::ECT){
            // Since we have reset m_borrowing we need to recompute the extensions.
            // To do so we need to recompute m_area_mod and m_flag_ext_face since they have been changed
            // since the last time ComputeFaceExtensions has been called. For this reason
            // we call ComputeFaceAreas, ScaleAreas and MarkCells before ComputeFaceExtensions
            ComputeFaceAreas;
            ScaleAreas;
            MarkCells();
            ComputeFaceExtensions();
        }
```

Comment (roelof-groenewald) [inline Source/Parallelization/WarpXRegrid.cpp]: No problem at all. The functions `ComputeFaceAreas()` and `ScaleAreas()` are called in the lines above this block. Should we remove them from there since they are not needed if `WarpX::maxwell_solver_id != MaxwellSolverAlgo::ECT`?

**Review by lgiacome — CHANGES_REQUESTED** [review]
I just added a minor change, after which we should be done with the EB

File: Source/Parallelization/WarpXRegrid.cpp (hunk 6 above)
Comment (lgiacome) [reply Source/Parallelization/WarpXRegrid.cpp]: Oh my bad, I overlooked that. If they are already called outside they are not needed inside

Comment (roelof-groenewald) [reply Source/Parallelization/WarpXRegrid.cpp]: Sounds good!

Comment (lgiacome) [inline Source/Parallelization/WarpXRegrid.cpp]: This takes care of doing all the initialization in the different cases and also of initializing the geometric data in the guard cells.
Sorry for the messy review but it took me a second

**Comment by lgiacome** [comment]
Hi @roelof-groenewald, I think we are still missing something for the re-initialization of the EB data in the guard cells. I sent a PR to your branch in which I take care of this.

**Review by lgiacome — APPROVED** [review]
Thanks for integrating the new changes and I apologize for the initial confusion.
I'll approve 😄

**Comment by roelof-groenewald** [comment]
@lgiacome Thanks for the review and your help getting this all squared away. As I mentioned in an earlier comment it seems to make sense to consolidate all the EB data calculations in a single function that can be called from both `WarpX::InitLevelData` and `WarpX::RemakeLevel`. That change actually looked quick and simple enough that I figured the code clean-up benefit from doing it makes it worth also squeezing that into this PR. Hopefully this change doesn't break anything :)

**Comment by lgiacome** [comment]
@roelof-groenewald this is really great, thanks! I should have done that a long time ago...

File: Source/Initialization/WarpXInitData.cpp [hunk 7]
```diff
@@ -869,3 +834,43 @@ void WarpX::CheckGuardCells(amrex::MultiFab const& mf)
...
+            ScaleEdges();
+            ScaleAreas();
+
+            const auto &period = Geom(lev).periodicity();
+            WarpXCommUtil::FillBoundary(*m_edge_lengths[lev][0], guard_cells.ng_alloc_EB, period);
+            WarpXCommUtil::FillBoundary(*m_edge_lengths[lev][1], guard_cells.ng_alloc_EB, period);
+            WarpXCommUtil::FillBoundary(*m_edge_lengths[lev][2], guard_cells.ng_alloc_EB, period);
+            WarpXCommUtil::FillBoundary(*m_face_areas[lev][0], guard_cells.ng_alloc_EB, period);
+            WarpXCommUtil::FillBoundary(*m_face_areas[lev][1], guard_cells.ng_alloc_EB, period);
+            WarpXCommUtil::FillBoundary(*m_face_areas[lev][2], guard_cells.ng_alloc_EB, period);
```
Comment (PhilMiller) [inline Source/Initialization/WarpXInitData.cpp:856]: Do any of these need to be guarded based on dimension? The 0,1,2 makes me think this might misbehave in fewer than 3 dimensions.

File: Source/WarpX.H [hunk 8]
```diff
@@ -745,6 +745,16 @@ public:
          amrex::ParserExecutor<3> const& zfield_parser,
          std::array< std::unique_ptr<amrex::MultiFab>, 3 > const& geom_data, const int lev);
 
+    /**
+     * \brief
+     * This function initializes and calculates grid quantities used along with
+     * EBs such as edge lengths, facec areas, distance to EB, etc. It also
```
Comment (PhilMiller) [inline Source/WarpX.H]: Typo 'facec'

Comment (PhilMiller) [reply Source/WarpX.H]:
```suggestion
     * EBs such as edge lengths, face areas, distance to EB, etc. It also
```

File: Source/Initialization/WarpXInitData.cpp (hunk 7 above)
Comment (roelof-groenewald) [reply Source/Initialization/WarpXInitData.cpp:856]: If these should be made dimension dependent I think that should go in a separate PR since that is different issue.

**Review by ax3l — APPROVED** [review]
Thank you for the fix and reviews! :tada:

File: Source/Initialization/WarpXInitData.cpp (hunk 7 above)
Comment (lgiacome) [reply Source/Initialization/WarpXInitData.cpp:856]: @PhilMiller 
I think it's going to be fine in every case. If you look into warpx.cpp (around line 1610) you'll see that all the three components of these vectors of multifab's are initialized independently of the number of dimensions. Probably the idea is that in fewer dimensionalities memory is not really an issue so it doesn't matter that we initialize some multifabs which are not really needed.

Comment (PhilMiller) [reply Source/Initialization/WarpXInitData.cpp:856]: As long as it's reasonably small amounts of data, I think that's fine.

Our 2D runs at Modern Electron are limited by memory capacity, though, since we're running a *lot* of particles.

Comment (lgiacome) [reply Source/Initialization/WarpXInitData.cpp:856]: I see thanks for the clarification.
Definitely worth a discussion at the next developers meeting :)
