### PR TITLE
Fix restart btd

### LINKED ISSUE #2468: BTD bug-fix for restart
PR #2356 fixed the starting position for BTD in the old implementation. 
This needs to be added in the new BTD implementation.

### LINKED ISSUE #2470: BTD checkpoint/restart
The new BTD implementation needs to be extended to ensure that checkpoint/restart is supported and accurate for the back-transformed snapshots.

### PR DESCRIPTION
**Pull request by RevathiJambunathan**
Please double check, but I think the following issues can be closed automatically by merging this PR (added by @EZoni):
- fixes #2468 
- fixes #2470

### CODE REVIEW

**Comment by n01r** [comment]
When I run this branch on Perlmutter with my small reproducer it still crashes:
However, the coordinates are much closer than before and it is not at buffer 0 that we crash but at buffer 8

From the **original** at step 1001:
```
 ibuffer  8 zboost  -0.002137229791 zlab 0.1119488229 boost lo -0.01766684518 boost hi 0.003931654719 zmin lab 0.1118165595 zmax lab 0.1120000333
 buffer 8 get z slice in domain 1
 ibuffer  8 zboost  -0.002137229791 zlab 0.1119488229 boost lo -0.01766684518 boost hi 0.003931654719 zmin lab 0.1118165595 zmax lab 0.1120000333
 warpx gettnew : 1.335457078e-11
 i buffer 8 hi k 1983
 ibuffer : 8 buiffer lo 0.1119445645 buffer hi 0.1119488313 current z lab 0.1119488229
...
... [and then further down] ...
...
 ibuffer  8 zboost  -0.002137229791 zlab 0.1119488229 boost lo -0.01766684518 boost hi 0.003931654719 zmin lab 0.1118165595 zmax lab 0.1120000333
...
... [and then it repeats] ...
...
 ibuffer  8 zboost  -0.002137229791 zlab 0.1119488229 boost lo -0.01766684518 boost hi 0.003931654719 zmin lab 0.1118165595 zmax lab 0.1120000333
```

From the **restart** at step 1001:
```
 ibuffer  8 zboost  -0.002137229791 zlab 0.1119488229 boost lo -0.01766684518 boost hi 0.003931654719 zmin lab 0.1118160266 zmax lab 0.1119995004
 buffer 8 get z slice in domain 1
 ibuffer  8 zboost  -0.002137229791 zlab 0.1119488229 boost lo -0.01766684518 boost hi 0.003931654719 zmin lab 0.1118160266 zmax lab 0.1119995004
 warpx gettnew : 1.335457078e-11
 i buffer 8 hi k 1983
 ibuffer : 8 buiffer lo 0.1119440316 buffer hi 0.1119482984 current z lab 0.1119488229
```

[small_reproducer_perlmutter_1_node_debug.zip](https://github.com/ECP-WarpX/WarpX/files/10915788/small_reproducer_perlmutter_1_node_debug.zip)

**Comment by n01r** [comment]
Thanks so much @RevathiJambunathan, the small reproducer can be successfully restarted now! :smile: :pray: 
I will try it again with a production-type run.

**Comment by n01r** [comment]
> I will try it again with a production-type run.

This worked, too! :slightly_smiling_face:

File: Source/Initialization/WarpXInitData.cpp [hunk 1]
```diff
@@ -402,7 +404,7 @@ WarpX::InitData ()
         m_macroscopic_properties->InitData();
     }
 
-    InitDiagnostics();
+    //InitDiagnostics();
```
Comment (EZoni) [inline Source/Initialization/WarpXInitData.cpp]: This line is commented out and can probably be removed.

File: Source/Diagnostics/BTDiagnostics.H [hunk 2]
```diff
@@ -169,11 +169,11 @@ private:
...
-    /** Vector of lab-frame time corresponding to each snapshot */
-    amrex::Vector<amrex::Real> m_t_lab;
-    /** Vector of user-defined physical region for diagnostics in lab-frame
-     *  for each back-transformed snapshot */
-    amrex::Vector<amrex::RealBox> m_snapshot_domain_lab;
+    ///** Vector of lab-frame time corresponding to each snapshot */
+    //amrex::Vector<amrex::Real> m_t_lab;
+    ///** Vector of user-defined physical region for diagnostics in lab-frame
+    // *  for each back-transformed snapshot */
+    //amrex::Vector<amrex::RealBox> m_snapshot_domain_lab;
```
Comment (EZoni) [inline Source/Diagnostics/BTDiagnostics.H]: These lines are commented out and can probably be removed.

File: Source/Diagnostics/BTDiagnostics.cpp [hunk 3]
```diff
@@ -461,20 +467,23 @@ BTDiagnostics::InitializeBufferData ( int i_buffer , int lev)
...
+        // lie close to the cell-centers in the lab-frame grid instead of on the edge of cell.
+        amrex::Real new_hi = m_snapshot_domain_lab[i_buffer].hi(m_moving_window_dir)
+                           + 0.5_rt * dz_lab(warpx.getdt(lev), ref_ratio[m_moving_window_dir]);
+        m_snapshot_domain_lab[i_buffer].setHi(m_moving_window_dir,new_hi);
+        amrex::Real new_lo = m_snapshot_domain_lab[i_buffer].hi(m_moving_window_dir) -
+                             num_z_cells_in_snapshot *
+                             dz_lab(warpx.getdt(lev), ref_ratio[m_moving_window_dir]);
+        m_snapshot_domain_lab[i_buffer].setLo(m_moving_window_dir, new_lo);
+    } else {
+    }
```
Comment (EZoni) [inline Source/Diagnostics/BTDiagnostics.cpp]: As noted by CodeQL, this `else` block is empty. Do we need it? Or can we just keep the first `if` block alone?

**Review by EZoni — COMMENTED** [review]
Thank you for fixing this, @RevathiJambunathan! The PR looks good to me, I just left a couple of minor comments, some also already covered by CodeQL. I would be in favor of merging this soon. First step would be to mark it as "ready for review" so that we see if CI has any issues.

**Comment by n01r** [comment]
Hey @RevathiJambunathan, after we chatted about how my bigger production run failed, I recompiled with debug symbols, let it run and again it failed at step 23 after the restart. I do have more detailed output of this now.

Here's the output file:
[output_2781479.txt](https://github.com/ECP-WarpX/WarpX/files/10996633/output_2781479.txt)

Error file:
[WarpXe.2781479.txt](https://github.com/ECP-WarpX/WarpX/files/10996636/WarpXe.2781479.txt)

One of the backtraces files that contains something
[Backtrace.75.txt](https://github.com/ECP-WarpX/WarpX/files/10996645/Backtrace.75.txt)

File: Source/Diagnostics/BTDiagnostics.cpp (hunk 3 above)
Comment (RevathiJambunathan) [reply Source/Diagnostics/BTDiagnostics.cpp]: fixed. Thank you

File: Source/Diagnostics/BTDiagnostics.H (hunk 2 above)
Comment (RevathiJambunathan) [reply Source/Diagnostics/BTDiagnostics.H]: I put these lines back and made them virtual functions in the main diag class

File: Source/Initialization/WarpXInitData.cpp (hunk 1 above)
Comment (RevathiJambunathan) [reply Source/Initialization/WarpXInitData.cpp]: done. thank you

**Comment by RevathiJambunathan** [comment]
I just rebased with upstream/development as well

**Comment by ax3l** [comment]
Thanks! Do you have time to fix the unused param warnings today? :)

File: Source/Diagnostics/BTDiagnostics.H [hunk 4]
```diff
@@ -310,6 +314,12 @@ private:
         return ( m_buffer_counter[i_buffer] == 0) ;
     }
 
+    amrex::Vector<int> m_first_flush_after_restart;
```
Comment (ax3l) [inline Source/Diagnostics/BTDiagnostics.H:325]: Can you please add 4 doxygen strings to the 3 new member vars and 1 new function?

File: Source/Diagnostics/BTDiagnostics.H [hunk 5]
```diff
@@ -388,5 +398,17 @@ private:
     void RedistributeParticleBuffer (const int i_buffer);
     void UpdateVarnamesForRZopenPMD();
 
+    amrex::Real gettlab (int i_buffer) override {return m_t_lab[i_buffer];}
```
Comment (ax3l) [inline Source/Diagnostics/BTDiagnostics.H:415]: Can you add docstrings here as well?

File: Source/Diagnostics/Diagnostics.H [hunk 6]
```diff
@@ -104,6 +106,21 @@ public:
     void FilterComputePackFlush (int step, bool force_flush=false);
     /** Whether the last timestep is always dumped */
     bool DoDumpLastTimestep () const {return  m_dump_last_timestep;}
+    int getnumbuffers() {return m_num_buffers;}
```
Comment (ax3l) [inline Source/Diagnostics/Diagnostics.H:110]: Since this is the Diagnostics general interface class, you add docstrings here? :)

File: Source/Diagnostics/MultiDiagnostics.H [hunk 7]
```diff
@@ -37,6 +37,9 @@ public:
     void InitializeFieldFunctors (int lev);
     /** Start a new iteration, i.e., dump has not been done yet. */
     void NewIteration ();
+    Diagnostics& GetDiag(int idiag) {return *alldiags[idiag]; }
```
Comment (ax3l) [inline Source/Diagnostics/MultiDiagnostics.H:40]: Please add Doxygen strings

File: Source/Diagnostics/BTDiagnostics.H (hunk 4 above)
Comment (RevathiJambunathan) [reply Source/Diagnostics/BTDiagnostics.H:325]: I have added it in the diagnostics.H where they are virtual methods. I will add for the 3 new member vars now. 
For the functions that are virtual methods in Diagnostics.H and we override them here, should we repeat doxygen?

File: Source/Diagnostics/BTDiagnostics.H (hunk 5 above)
Comment (RevathiJambunathan) [reply Source/Diagnostics/BTDiagnostics.H:415]: this I added in Diagnostics.H 
do we repeat here. no big deal if we have to. I ll just paste those doxygen lines here

File: Source/Diagnostics/Diagnostics.H (hunk 6 above)
Comment (RevathiJambunathan) [reply Source/Diagnostics/Diagnostics.H:110]: yes. thats what i have done now :)

File: Source/Diagnostics/BTDiagnostics.H (hunk 4 above)
Comment (ax3l) [reply Source/Diagnostics/BTDiagnostics.H:325]: I think that makes sense, no need to repeat if overridden :)

**Review by ax3l — APPROVED** [review]
Thanks a lot, Reva!! :rocket: :sparkles:
