### PR TITLE
ParticleHistogram: Fix Performance Regression

### LINKED ISSUE #1693: Particle Histogram: Performance Regression
We are running 2D3V simulations on 20 cori nodes with OpenMP acceleration and see a performance regression once we add the reduced diagnostics for particle histograms:
```
# histograms with 2.0 degree acceptance angle in fw direction
# 2 deg * pi / 180 : 0.03490658503 rad
# half-angle +/-   : 0.017453292515 rad
# 
warpx.reduced_diags_names                       = histuH histue
histuH.type                                     = ParticleHistogram
histuH.intervals                                = 50
histuH.path                                     = "./histograms/"
histuH.species                                  = hydrogen
histuH.bin_number                               = 1000
histuH.bin_min                                  = 0.0
histuH.bin_max                                  = 1.1
histuH.histogram_function(t,x,y,z,ux,uy,uz) = "sqrt(ux*ux+uy*uy+uz*uz)"
histuH.filter_function(t,x,y,z,ux,uy,uz) = "abs(acos(uz / sqrt(ux*ux+uy*uy+uz*uz))) <= 0.017453"

histue.type                                     = ParticleHistogram
histue.intervals                                = 50
histue.path                                     = "./histograms/"
histue.species                                  = electrons
histue.bin_number                               = 1000
histue.bin_min                                  = 0.0
histue.bin_max                                  = 300
histue.histogram_function(t,x,y,z,ux,uy,uz) = "sqrt(ux*ux+uy*uy+uz*uz)"
histue.filter_function(t,x,y,z,ux,uy,uz) = "abs(acos(uz / sqrt(ux*ux+uy*uy+uz*uz))) <= 0.017453"
```

The simulation time goes roughly up by 8x.

When commenting out the `filter_function`, the runtime again increases by 1.5x - so the issue must be inside the binning itself.

### PR DESCRIPTION
**Pull request by Yin-YinjianZhao**
This PR fixes #1693 by "reverting" the outer and the inner loops.
In addition, it is found that `m_data` should be set to zero initially before computing.

- [ ] tested on CPUs
- [ ] tested on GPUs

### CODE REVIEW

File: Source/Diagnostics/ReducedDiags/ParticleHistogram.cpp [hunk 1]
```diff
@@ -159,30 +159,31 @@ void ParticleHistogram::ComputeDiags (int step)
...
-            auto const f1 = bin_min + bin_size*i;
-            auto const f2 = bin_min + bin_size*(i+1);
-            if ( f > f1 && f < f2 ) {
-                if ( is_unity_particle_weight ) return 1.0_rt;
-                else return w;
-            } else return 0.0_rt;
-        });
+    // compute the histogram
+    for ( int i = 0; i < m_bin_num; ++i ) {
+        m_data[i] = 0.0_rt;
```
Comment (ax3l) [inline Source/Diagnostics/ReducedDiags/ParticleHistogram.cpp]: cc @atmyers @MaxThevenet 

I am surprised we use a `std::vector` for `m_data` here. Wouldn't it be way more efficient to use a device vector and copying it down after the `ReduceSum` (now: `ParallelFor`) to `m_data`?

File: Source/Diagnostics/ReducedDiags/ParticleHistogram.cpp [hunk 2]
```diff
@@ -159,30 +159,31 @@ void ParticleHistogram::ComputeDiags (int step)
...
+        if (!fun_filterparser(p, amrex::RandomEngine())) {return 0.0_rt;}
+        // continue function if particle is not filtered out
+        auto const w  = p.rdata(PIdx::w);
+        amrex::ParticleReal x, y, z;
+        get_particle_position(p, x, y, z);
+        auto const ux = p.rdata(PIdx::ux)/PhysConst::c;
+        auto const uy = p.rdata(PIdx::uy)/PhysConst::c;
+        auto const uz = p.rdata(PIdx::uz)/PhysConst::c;
+        auto const f = fun_partparser(t,x,y,z,ux,uy,uz);
+        int i = int(std::floor((f-bin_min)/bin_size));
```
Comment (ax3l) [inline Source/Diagnostics/ReducedDiags/ParticleHistogram.cpp]: Avoiding memory violations if particles are outside of the set min/max range:
```suggestion

        int i = int(std::floor((f-bin_min)/bin_size));
        // all entries larger than bin_max go into the last bin
        i = i < m_bin_num ? i : m_bin_num-1;
        // all entries smaller than bin_min go into the first bin
        i = i > 0 ? i : 0;
```

Comment (Yin-YinjianZhao) [reply Source/Diagnostics/ReducedDiags/ParticleHistogram.cpp]: @ax3l 
I actually think it is more reasonable to ignore those particles that are outside of the set.
Previously, I often intent to set a smaller range, so it actually behaves like a filter to some extent.

Comment (ax3l) [reply Source/Diagnostics/ReducedDiags/ParticleHistogram.cpp]: Both is possible. If you like to ignore out-of-range particles, you need to handle it by not calling `atomicAdd` anymore, otherwise it's an out-of-bounds access to the data array.

But since we have actual filters now, I would change the behavior - overflow and underflow bins are extremely useful.
We could add +2 bins for those as many histogram libs do as well (one at the beginning and one at the end of the spectrum).

File: Source/Diagnostics/ReducedDiags/ParticleHistogram.cpp [hunk 3]
```diff
@@ -159,30 +159,32 @@ void ParticleHistogram::ComputeDiags (int step)
...
-            if ( f > f1 && f < f2 ) {
-                if ( is_unity_particle_weight ) return 1.0_rt;
-                else return w;
-            } else return 0.0_rt;
-        });
+    // compute the histogram
+    for ( int i = 0; i < m_bin_num; ++i ) {
+        m_data[i] = 0.0_rt;
     }
+    ReduceSum( myspc,
```
Comment (ax3l) [inline Source/Diagnostics/ReducedDiags/ParticleHistogram.cpp]: This needs to become a `ParallelFor` over the number of particles now.

See this example:
https://github.com/ECP-WarpX/WarpX/blob/2cfc0673f0fc2a55e2b223ee792d03e3f7666631/Source/Particles/PhysicalParticleContainer.cpp#L1657-L1678

File: Source/Diagnostics/ReducedDiags/ParticleHistogram.cpp (hunk 2 above)
Comment (ax3l) [reply Source/Diagnostics/ReducedDiags/ParticleHistogram.cpp]: Update: `if ( i<0 || i>=m_bin_num )` handling is ok for now, we can add overflow bins in a follow-up.

File: Source/Diagnostics/ReducedDiags/ParticleHistogram.cpp (hunk 1 above)
Comment (atmyers) [reply Source/Diagnostics/ReducedDiags/ParticleHistogram.cpp]: It made sense given the way the function was written before, but now that this is using atomics I agree that we want to use a `amrex::Gpu::DeviceVector` here.

File: Source/Diagnostics/ReducedDiags/ParticleHistogram.cpp [hunk 4]
```diff
@@ -143,46 +146,77 @@ void ParticleHistogram::ComputeDiags (int step)
...
+                    } else {
+                        amrex::HostDevice::Atomic::Add(&dptr_data[bin], w);
+                    }
+                });
+            }
+        }
     }
+
+    // blocking copy from device to host
+    amrex::Gpu::copy(amrex::Gpu::deviceToDevice,
```
Comment (ax3l) [inline Source/Diagnostics/ReducedDiags/ParticleHistogram.cpp]: Upsi, typo:
```suggestion
    amrex::Gpu::copy(amrex::Gpu::deviceToHost,
```

File: Source/Diagnostics/ReducedDiags/ParticleHistogram.cpp [hunk 5]
```diff
@@ -143,46 +146,78 @@ void ParticleHistogram::ComputeDiags (int step)
...
+                    auto const uy = d_uy[i] / PhysConst::c;
+                    auto const uz = d_uz[i] / PhysConst::c;
+
+                    // don't count a particle if it is filtered out
+                    if (!fun_filterparser(t, x, y, z, ux, uy, uz)) return;
+                    // continue function if particle is not filtered out
+                    auto const f = fun_partparser(t, x, y, z, ux, uy, uz);
+
+                    // determine particle bin
+                    int const bin = int(std::floor((f-bin_min)/bin_size));
```
Comment (ax3l) [inline Source/Diagnostics/ReducedDiags/ParticleHistogram.cpp]: For DPC++ from `AMReX_Math.H`:
```suggestion
                    int const bin = int(Math::floor((f-bin_min)/bin_size));
```

File: Source/Diagnostics/ReducedDiags/ParticleHistogram.cpp [hunk 6]
```diff
@@ -11,12 +11,15 @@
 #include "Utils/WarpXUtil.H"
 #include "Particles/Filter/FilterFunctors.H"
 
-#include <AMReX_REAL.H>
+#include <AMReX_GpuContainers.H>
 #include <AMReX_ParticleReduce.H>
```
Comment (ax3l) [inline Source/Diagnostics/ReducedDiags/ParticleHistogram.cpp:16]:
```suggestion
#include <AMReX_Math.H>
#include <AMReX_ParticleReduce.H>
```

File: Source/Diagnostics/ReducedDiags/ParticleHistogram.cpp [hunk 7]
```diff
@@ -143,46 +147,78 @@ void ParticleHistogram::ComputeDiags (int step)
...
+                    if (!fun_filterparser(t, x, y, z, ux, uy, uz)) return;
+                    // continue function if particle is not filtered out
+                    auto const f = fun_partparser(t, x, y, z, ux, uy, uz);
+
+                    // determine particle bin
+                    int const bin = int(Math::floor((f-bin_min)/bin_size));
+                    if ( bin<0 || bin>=num_bins ) return; // discard if out-of-range
+
+                    if ( is_unity_particle_weight ) {
+                        amrex::HostDevice::Atomic::Add(&dptr_data[bin], 1.0_rt);
```
Comment (atmyers) [inline Source/Diagnostics/ReducedDiags/ParticleHistogram.cpp:213]: This is probably not the most efficient way to do this on the host (we could be doing one atomic per bin instead atomics on a per particle basis), but we could cross that bridge when we come to it.

**Review by atmyers — APPROVED** [review]

File: Source/Diagnostics/ReducedDiags/ParticleHistogram.cpp (hunk 7 above)
Comment (ax3l) [reply Source/Diagnostics/ReducedDiags/ParticleHistogram.cpp:213]: Ouch, this should be a device atomic add now! forgot to change
```suggestion
                        amrex::Gpu::Atomic::AddNoRet(&dptr_data[bin], 1.0_rt);
```

Comment (atmyers) [reply Source/Diagnostics/ReducedDiags/ParticleHistogram.cpp:213]: `amrex::HostDevice::Atomic:Add` is the correct function to call here. When compiled with AMREX_USE_GPU, it does an atomic add on the device, and otherwise it does atomic add on the host. What I meant is that, when `AMREX_USE_GPU=FALSE`, it may be be better to have each thread compute separate histograms, then do a reduction on each bin at the end. But I don't think exploring that needs to be part of this PR.

Comment (ax3l) [reply Source/Diagnostics/ReducedDiags/ParticleHistogram.cpp:213]: Oh, should not have worked on this parallel to our meeting. Agreed, will add a comment at least!
