### PR TITLE
Lassen: No MPI 4+ Support

### LINKED ISSUE #5728: Rebuilding on Lassen
## Description
An old executable has been running noticeably slower on Lassen, have been trying to rebuild it. However the recompiled executable gives a runtime error I do not recognize, files attached here. 

## System information
- Operating system (name and version):
  - [x] Linux: e.g., Ubuntu 22.04 LTS
  - [ ] macOS: e.g., macOS Monterey 12.4
  - [ ] Windows: e.g., Windows 11 Pro
- Version of WarpX: e.g., latest, 24.10, etc.
- Installation method:
  - [ ] Conda
  - [ ] Spack
  - [ ] PyPI
  - [ ] Brew
  - [x] From source with CMake
  - [ ] Module system on an HPC cluster
- Other dependencies: yes/no, describe
- Computational resources:
  - [ ] CPU
  - [x] GPU: e.g., NVIDIA, AMD, etc.

If you encountered the issue on an HPC cluster, please check our [HPC documentation](https://warpx.readthedocs.io/en/latest/install/hpc.html) to see if your HPC cluster is already supported.

If you encountered the issue installing from source with CMake, please provide the output of the following steps:
1. buildsystem generation: output of `cmake --fresh -S . -B build` (include your specific build options, e.g., `-DWarpX_DIMS=3`)
2. project build: output of `cmake --build build` (include your specific build options, e.g., `-j 4`)

If applicable, please add any additional information about your software environment:
- [x] CMake: e.g., 3.29.0
- [ ] C++ compiler: e.g., GNU 11.3 with NVCC 12.0.76
- [ ] Python: e.g., CPython 3.12
- [ ] MPI: e.g., OpenMPI 4.1.1
- [ ] FFTW: e.g., 3.3.10
- [ ] HDF5: e.g., 1.14.0
- [ ] ADIOS2: e.g., 2.10.0
- Other dependencies: yes/no, describe

## Additional information
```
/.bashrc: line 52: [: ==: unary operator expected
2: 1: errno 14 pid 56498
2: 1: warpx.rz: /__SMPI_build_dir_______________________________________/ibmsrc/pami/ibm-pami/buildtools/pami_build_port/../pami/components/devices/shmem/shaddr/CMAShaddr.h:164: size_t PAMI::Device::Shmem::CMAShaddr::read_impl(PAMI::Memregion*, size_t, PAMI::Memregion*, size_t, size_t, bool*): Assertion `cbytes > 0' failed.
2: 1: SIGABRT
```

[warpx_run.zip](https://github.com/user-attachments/files/19066034/warpx_run.zip)

### PR DESCRIPTION
**Pull request by ax3l**
- [x] `mpi4py>=4.0` was released and supports (and requires) MPI 4 features. But Lassen does not support MPI 4 in the IBM Spectrum rolling releases.
Thus, limit the upper versions of `mpi4py` for now.

- [x] Making the compilers for `h5py` a bit more robust, using the Lassen-specific wrapper name. https://hpc.llnl.gov/documentation/tutorials/using-lc-s-sierra-systems#Compilers

- [x] The Lassen TOSS4 upgrade never was shipped, so we can simplify our paths and names again. Some confusion was left here in paths that prevented a smooth install

cc @bzdjordje 

Fix #5728

### To Do

- [x] compiles
- [ ] exe: runs without errors
- [ ] python: runs without errors

### CODE REVIEW

File: Tools/machines/lassen-llnl/install_v100_dependencies_toss3.sh [hunk 1]
```diff
@@ -119,13 +119,15 @@ python3 -m pip install --upgrade build
...
+python3 -m pip install --upgrade "cython>=3"
+python3 -m pip install --upgrade "numpy<2"  # for openPMD-api 0.15.2
 python3 -m pip install --upgrade pandas
 CMAKE_PREFIX_PATH=/usr/lib64:${CMAKE_PREFIX_PATH} python3 -m pip install --upgrade -Ccompile-args="-j10" -Csetup-args=-Dblas=BLAS -Csetup-args=-Dlapack=BLAS scipy
-python3 -m pip install --upgrade mpi4py --no-cache-dir --no-build-isolation --no-binary mpi4py
-python3 -m pip install --upgrade openpmd-api
-CC=mpicc H5PY_SETUP_REQUIRES=0 HDF5_DIR=${SW_DIR}/hdf5-1.14.1.2 HDF5_MPI=ON python3 -m pip install --upgrade h5py --no-cache-dir --no-build-isolation --no-binary h5py
+# Lassen MPI does not suppport MPI v4
+MPI4PY_BUILD_BACKEND="scikit-build-core" python3 -m pip install --upgrade "mpi4py<4" --no-cache-dir --no-build-isolation --no-binary mpi4py
+python3 -m pip install --upgrade openpmd-api==0.15.2
```
Comment (ax3l) [inline Tools/machines/lassen-llnl/install_v100_dependencies_toss3.sh]: This line and `numpy<2` can be loosened if https://github.com/openPMD/openPMD-api/pull/1734 works.

Comment (ax3l) [reply Tools/machines/lassen-llnl/install_v100_dependencies_toss3.sh]: worked, can  be reset

**Comment by ax3l** [comment]
Hm, I see segfaults of the form
```
 3: /usr/tce/packages/spectrum-mpi/ibm/spectrum-mpi-rolling-release/container/../lib/pami_port/libpami.so.3(_ZN4PAMI6Device5Shmem6PacketINS_4Fifo10FifoPacketILj64ELj4096EEEE12writePayloadERS5_Pvm+0xe8
) [0x200055f46fb8]
    ?? ??:0

 4: /usr/tce/packages/spectrum-mpi/ibm/spectrum-mpi-rolling-release/container/../lib/pami_port/libpami.so.3(_ZN4PAMI6Device9Interface11PacketModelINS0_5Shmem11PacketModelINS0_11ShmemDeviceINS_4Fifo8Wr
apFifoINS6_10FifoPacketILj64ELj4096EEENS_7Counter15IndirectBoundedINS_6Atomic12NativeAtomicEEELj256EEENSA_8IndirectINSA_6NativeEEENS3_9CMAShaddrELj256ELj512EEEEEE15postMultiPacketILj512EEEbRAT__hPFvPv
SQ_13pami_result_tESQ_mmSQ_mSQ_m+0x304) [0x200055f65ae4]
    ?? ??:0

 5: /usr/tce/packages/spectrum-mpi/ibm/spectrum-mpi-rolling-release/container/../lib/pami_port/libpami.so.3(_ZN4PAMI8Protocol4Send11EagerSimpleINS_6Device5Shmem11PacketModelINS3_11ShmemDeviceINS_4Fifo
8WrapFifoINS7_10FifoPacketILj64ELj4096EEENS_7Counter15IndirectBoundedINS_6Atomic12NativeAtomicEEELj256EEENSB_8IndirectINSB_6NativeEEENS4_9CMAShaddrELj256ELj512EEEEELNS1_15configuration_tE1EE11simple_i
mplEP11pami_send_t+0x434) [0x200055f78e74]
    ?? ??:0

 6: /usr/tce/packages/spectrum-mpi/ibm/spectrum-mpi-rolling-release/container/../lib/pami_port/libpami.so.3(_ZN4PAMI8Protocol4Send5EagerINS_6Device5Shmem11PacketModelINS3_11ShmemDeviceINS_4Fifo8WrapFi
foINS7_10FifoPacketILj64ELj4096EEENS_7Counter15IndirectBoundedINS_6Atomic12NativeAtomicEEELj256EEENSB_8IndirectINSB_6NativeEEENS4_9CMAShaddrELj256ELj512EEEEENS3_3IBV14GpuPacketModelINSN_6DeviceELb0EEE
E9EagerImplILNS1_15configuration_tE1ELb1EE6simpleEP11pami_send_t+0x2c) [0x200055f7916c]
    ?? ??:0

 7: /usr/tce/packages/spectrum-mpi/ibm/spectrum-mpi-rolling-release/container/../lib/pami_port/libpami.so.3(PAMI_Send+0x58) [0x200055ea5758]
    ?? ??:0

 8: /usr/tce/packages/spectrum-mpi/ibm/spectrum-mpi-rolling-release/container/../lib/spectrum_mpi/mca_pml_pami.so(pml_pami_send+0x6d8) [0x200055cdf6c8]
    ?? ??:0

 9: /usr/tce/packages/spectrum-mpi/ibm/spectrum-mpi-rolling-release/container/../lib/spectrum_mpi/mca_pml_pami.so(mca_pml_pami_isend+0x568) [0x200055ce0658]
    ?? ??:0

10: /usr/tce/packages/spectrum-mpi/ibm/spectrum-mpi-rolling-release/lib/libmpi_ibm.so.3(MPI_Isend+0x160) [0x200051fb4750]
    ?? ??:0

11: ./warpx.rz() [0x1079b6b8]
    amrex::ParallelDescriptor::Message amrex::ParallelDescriptor::Asend<char>(char const*, unsigned long, int, int, ompi_communicator_t*) at ??:?

12: ./warpx.rz() [0x10383bf8]
    void amrex::communicateParticlesStart<amrex::ParticleContainer_impl<amrex::SoAParticle<7, 0>, 7, 0, amrex::ArenaAllocator, amrex::DefaultAssignor>, amrex::PODVector<char, amrex::PolymorphicArenaAllocator<char> >, amrex::PODVector<char, amrex::PolymorphicArenaAllocator<char> >, 0>(amrex::ParticleContainer_impl<amrex::SoAParticle<7, 0>, 7, 0, amrex::ArenaAllocator, amrex::DefaultAssignor> const&, amrex::ParticleCopyPlan&, amrex::PODVector<char, amrex::PolymorphicArenaAllocator<char> > const&, amrex::PODVector<char, amrex::PolymorphicArenaAllocator<char> >&) [clone .isra.0] at tmpxft_00018e9c_00000000-6_MultiParticleContainer.cudafe1.cpp:?

13: ./warpx.rz() [0x10385dcc]
    amrex::ParticleContainer_impl<amrex::SoAParticle<7, 0>, 7, 0, amrex::ArenaAllocator, amrex::DefaultAssignor>::RedistributeGPU(int, int, int, int, bool) at ??:?

```

**Comment by ax3l** [comment]
and
```
3: 1: warpx.rz: /__SMPI_build_dir_______________________________________/ibmsrc/pami/ibm-pami/buildtools/pami_build_port/../pami/components/devices/shmem/shaddr/CMAShaddr.h:164: size_t PAMI::Device::Shmem::CMAShaddr::read_impl(PAMI::Memregion*, size_t, PAMI::Memregion*, size_t, size_t, bool*): Assertion `cbytes > 0' failed.
```

**Comment by ax3l** [comment]
They go away if I remove the `-M "-gpu"` from the `jsrun` line.
```
  -M, --smpiargs=<SMPI args> Quoted argument list meaningful for Spectrum MPI
                             applications.
```

**Comment by ax3l** [comment]
@bzdjordje this fixes it for me. Maybe all you need to do is update your `jsrun` line.

**Comment by ax3l** [comment]
Merging to show fully working example to the user in the live docs & mainline scripts.
https://warpx.readthedocs.io/en/latest/install/hpc/lassen.html
