### PR TITLE
Always update guard cells in WarpXSumGuardCells

### LINKED ISSUE #3900: PEC boundaries: Copy values in guard cells
With PEC boundaries, charge and current density deposited in guard cells outside the domain (inside PEC boundaries) are either reflected back into the simulation domain or subtracted from internal cells (to represent image charge contributions). Currently, the values in guard cells at the corner of simulation boxes are not gathered during the `SumBoundary` call, which means that small amounts of density is lost in those overlapping regions.

[cc. @WeiqunZhang ]

### LINKED ISSUE #4833: MLMG solver fails to converge with particles close to PEC boundary
When running this script:
[inputs.txt](https://github.com/ECP-WarpX/WarpX/files/14899064/inputs.txt)
with:
```
mpirun -np 2 ./warpx.3d.MPI.OMP.DP.PDP.OPMD.QED inputs warpx.numprocs = 1 2 1
```
the solver fails to converge at STEP 1:
```
STEP 1 starts ...
MLMG: # of AMR levels: 1
      # of MG levels on the coarsest AMR level: 6
MLMG: Initial rhs               = 2.024118383e+24
MLMG: Initial residual (resid0) = 1.156456482e+24
MLMG: Iteration   1 Fine resid/bnorm = 0.0006712462953
MLMG: Iteration   2 Fine resid/bnorm = 0.0002564242782
MLMG: Iteration   3 Fine resid/bnorm = 0.0002565438993
MLMG: Iteration   4 Fine resid/bnorm = 0.0002565457734
MLMG: Iteration   5 Fine resid/bnorm = 0.0002565458005
MLMG: Iteration   6 Fine resid/bnorm = 0.0002565458009
MLMG: Iteration   7 Fine resid/bnorm = 0.0002565458009
MLMG: Iteration   8 Fine resid/bnorm = 0.0002565458009
```

Interestingly, this bug disappears in the following cases:
- When removing the call to `ApplyRhoFieldBoundary` here: https://github.com/ECP-WarpX/WarpX/blob/development/Source/FieldSolver/ElectrostaticSolver.cpp#L233
- When switching from `warpx.do_electrostatic = labframe` to `warpx.do_electrostatic = relativistic`. (Note that that the relativistic Poisson solver does not call `ApplyRhoFieldBoundary` directly.)
- When using only 1 MPI rank
- When switching from `algo.particle_shape = 2` to `algo.particle_shape = 1`

### PR DESCRIPTION
**Pull request by RemiLehe**
For performance reasons, we were not updating the guard cells when calling `WarpXSumGuardCells` on `Rho` and `J` (unless PSATD was used).

However, this leads to bugs as shown in #3900 and #4833. 

This PR fixes #3900 and fixes #4833, by always updating the guard cells.

### CODE REVIEW

File: Source/Parallelization/WarpXSumGuardCells.cpp [hunk 1]
```diff
@@ -19,14 +19,7 @@ WarpXSumGuardCells(amrex::MultiFab& mf, const amrex::Periodicity& period,
...
 {
-    amrex::IntVect n_updated_guards;
-
-    // Update both valid cells and guard cells
-    if (WarpX::electromagnetic_solver_id == ElectromagneticSolverAlgo::PSATD) {
-        n_updated_guards = mf.nGrowVect();
-    } else {  // Update only the valid cells
-        n_updated_guards = amrex::IntVect::TheZeroVector();
-    }
+    amrex::IntVect n_updated_guards = mf.nGrowVect();
```
Comment (RemiLehe) [inline Source/Parallelization/WarpXSumGuardCells.cpp]:
```suggestion
    amrex::IntVect const n_updated_guards = mf.nGrowVect();
```

File: Source/Parallelization/WarpXSumGuardCells.cpp [hunk 2]
```diff
@@ -37,14 +30,7 @@ WarpXSumGuardCells(amrex::MultiFab& dst, amrex::MultiFab& src,
...
 {
-    amrex::IntVect n_updated_guards;
-
-    // Update both valid cells and guard cells
-    if (WarpX::electromagnetic_solver_id == ElectromagneticSolverAlgo::PSATD) {
-        n_updated_guards = dst.nGrowVect();
-    } else {  // Update only the valid cells
-        n_updated_guards = amrex::IntVect::TheZeroVector();
-    }
+    amrex::IntVect n_updated_guards = dst.nGrowVect();
```
Comment (RemiLehe) [inline Source/Parallelization/WarpXSumGuardCells.cpp]:
```suggestion
    amrex::IntVect const n_updated_guards = dst.nGrowVect();
```

**Review by roelof-groenewald — APPROVED** [review]
That's a decently easy fix 😃

**Review by lucafedeli88 — APPROVED** [review]
Thanks for this PR

**Review by lucafedeli88 — COMMENTED** [review]
ah, the PR actually breaks some tests...

File: Regression/WarpX-tests.ini [hunk 3]
```diff
@@ -977,7 +977,7 @@ analysisRoutine = Examples/Tests/plasma_lens/analysis.py
 [hard_edged_quadrupoles]
 buildDir = .
 inputFile = Examples/Tests/AcceleratorLattice/inputs_quad_3d
-runtime_params =
+runtime_params = warpx.abort_on_warning_threshold=medium
```
Comment (RemiLehe) [inline Regression/WarpX-tests.ini]:
```suggestion
runtime_params =
```

File: Examples/Tests/ohm_solver_EM_modes/analysis_rz.py [hunk 4]
```diff
@@ -153,7 +153,7 @@ def process(it):
     amps = np.abs(F_kw[2, 1, len(kz)//2-2:len(kz)//2+2])
     print("Amplitude sample: ", amps)
     assert np.allclose(
-        amps, np.array([61.50945919, 19.74831134, 101.01820349, 10.8974811])
+        amps, np.array([ 61.02377286  19.80026021 100.47687017  10.83331295])
```
Comment (roelof-groenewald) [inline Examples/Tests/ohm_solver_EM_modes/analysis_rz.py]:
```suggestion
        amps, np.array([ 61.02377286,  19.80026021, 100.47687017,  10.83331295])
```

File: Examples/Physics_applications/capacitive_discharge/analysis_dsmc.py [hunk 5]
```diff
@@ -18,39 +18,30 @@
...
+    2.56415143e+14, 2.56259609e+14, 2.56264787e+14, 2.56619762e+14,
+    2.56992843e+14, 2.57102387e+14, 2.56719391e+14, 2.56255624e+14,
+    2.56276638e+14, 2.56350832e+14, 2.56295294e+14, 2.56153556e+14,
+    2.56170347e+14, 2.56246380e+14, 2.56088509e+14, 2.56121028e+14,
+    2.56423889e+14, 2.56597963e+14, 2.56470310e+14, 2.56419968e+14,
+    2.56625715e+14, 2.56711965e+14, 2.56651610e+14, 2.56750226e+14,
+    2.56743475e+14, 2.56616083e+14, 2.56830920e+14, 2.57164423e+14,
+    2.56868182e+14, 2.56749114e+14, 2.57108990e+14, 2.56791445e+14,
+    2.56203737e+14, 2.56114492e+14, 2.56630346e+14, 2.24843400e+14,
+    1.28200732e+14
```
Comment (roelof-groenewald) [inline Examples/Physics_applications/capacitive_discharge/analysis_dsmc.py]: I think a few lines got cut-off here:
```suggestion
       1.27945114e+14, 2.23583642e+14, 2.55392166e+14, 2.55655614e+14,
       2.55811304e+14, 2.55813038e+14, 2.55817129e+14, 2.55752279e+14,
       2.55912208e+14, 2.56079483e+14, 2.55932916e+14, 2.55822911e+14,
       2.55910910e+14, 2.55995538e+14, 2.56185960e+14, 2.56518490e+14,
       2.56843281e+14, 2.56847244e+14, 2.56317496e+14, 2.55995033e+14,
       2.56036918e+14, 2.56185305e+14, 2.56473454e+14, 2.56612720e+14,
       2.56460349e+14, 2.56162495e+14, 2.56154687e+14, 2.56351568e+14,
       2.56518116e+14, 2.56589716e+14, 2.56491198e+14, 2.56462652e+14,
       2.56475832e+14, 2.56502009e+14, 2.56512082e+14, 2.56400671e+14,
       2.56317027e+14, 2.56348890e+14, 2.56604754e+14, 2.56846626e+14,
       2.56749617e+14, 2.56563946e+14, 2.56508159e+14, 2.56706913e+14,
       2.56921135e+14, 2.56772946e+14, 2.56509222e+14, 2.56556290e+14,
       2.56632138e+14, 2.56452482e+14, 2.56371644e+14, 2.56363151e+14,
       2.56471549e+14, 2.56541772e+14, 2.56342768e+14, 2.56345629e+14,
       2.56415143e+14, 2.56259609e+14, 2.56264787e+14, 2.56619762e+14,
       2.56992843e+14, 2.57102387e+14, 2.56719391e+14, 2.56255624e+14,
       2.56276638e+14, 2.56350832e+14, 2.56295294e+14, 2.56153556e+14,
       2.56170347e+14, 2.56246380e+14, 2.56088509e+14, 2.56121028e+14,
       2.56423889e+14, 2.56597963e+14, 2.56470310e+14, 2.56419968e+14,
       2.56625715e+14, 2.56711965e+14, 2.56651610e+14, 2.56750226e+14,
       2.56886322e+14, 2.56839170e+14, 2.56469219e+14, 2.56254127e+14,
       2.56422126e+14, 2.56381502e+14, 2.56283046e+14, 2.56358078e+14,
       2.56454503e+14, 2.56810744e+14, 2.57281306e+14, 2.57314168e+14,
       2.57216217e+14, 2.57166645e+14, 2.56969293e+14, 2.56763128e+14,
       2.56479604e+14, 2.56454515e+14, 2.56670498e+14, 2.56378555e+14,
       2.56177400e+14, 2.56510462e+14, 2.56512126e+14, 2.56391975e+14,
       2.56717395e+14, 2.57024288e+14, 2.56901669e+14, 2.56632950e+14,
       2.56470315e+14, 2.56530515e+14, 2.56839839e+14, 2.57084249e+14,
       2.56897794e+14, 2.56360159e+14, 2.56251337e+14, 2.56628550e+14,
       2.56743475e+14, 2.56616083e+14, 2.56830920e+14, 2.57164423e+14,
       2.56868182e+14, 2.56749114e+14, 2.57108990e+14, 2.56791445e+14,
       2.56203737e+14, 2.56114492e+14, 2.56630346e+14, 2.24843400e+14,
       1.28200732e+14
```

File: Examples/Tests/AcceleratorLattice/inputs_quad_3d [hunk 6]
```diff
@@ -2,8 +2,8 @@ max_step = 50
 amr.n_cell = 8 8 32
 amr.max_level = 0
 geometry.dims = 3
-geometry.prob_lo     = -0.2 -0.2 0.
-geometry.prob_hi     = +0.2 +0.2 1.6
+geometry.prob_lo     = -0.2 -0.2 -0.025
+geometry.prob_hi     = +0.2 +0.2 1.575
```
Comment (RemiLehe) [inline Examples/Tests/AcceleratorLattice/inputs_quad_3d:6]: I changed the boundaries to avoid having the particle exactly at the edge of the simulation box.
