### PR TITLE
Fix Segfault: Create Particle Functor

### LINKED ISSUE #508: Illegal memory access in ParticleCreaction/CopyParticle.H on GPU
Hi,

I've compiled `WarpX` (dev branch) for GPU with the following line:
```
make USE_OMP=FALSE USE_GPU=TRUE DIM=2 DEBUG=TRUE -j22
```
Then, I run the ionization example `Examples/Modules/ionization/inputs.rt` under `cuda-gdb` with memcheck enabled. I got the following error message:

```
STEP 83 starts ...

CUDA Exception: Warp Illegal Address
The exception was triggered at PC 0x84978f0 (CopyParticle.H:66)

Thread 1 "main2d.gnu.DEBU" received signal CUDA_EXCEPTION_14, Warp Illegal Address.
[Switching focus to CUDA kernel 0, grid 172551, block (0,0,0), thread (14,0,0), device 0, sm 0, warp 3, lane 14]
0x0000000008497900 in copyParticle::operator() (this=0x6721e90, is=14, ip=0, pid_product=38673, p_source=0x7fff14a99270, p_product=0x7fff14801fc0)
    at /home/lfedeli/WW/WarpX/./Source/Particles/ParticleCreation/CopyParticle.H:66
66	        p_product.cpu() = m_cpuid;

```

Have you ever experienced something similar?

### PR DESCRIPTION
**Pull request by ax3l**
Fix #508: Copy over the full create-particle functor including its data via managed memory. Previously, we used a host-side vector to initialize the functors and then did not copy over the the state to device.

As always, this does not show up as an error on Summit but as a slowdown at runtime. This crashed with segfaults on all other GPU machines, first seen when accessing the `m_cpuid` member. Introduced in #463.

Co-street-credits to @MaxThevenet for pointers. :sparkles: I mean, pointers on where this could be coming from.

### CODE REVIEW

File: Source/Particles/ParticleCreation/ElementaryProcess.H [hunk 1]
```diff
@@ -65,7 +65,7 @@ public:
     void createParticles (
         int lev, const amrex::MFIter& mfi,
         std::unique_ptr< WarpXParticleContainer>& pc_source,
-        amrex::Vector<WarpXParticleContainer*> v_pc_product,
+        amrex::Gpu::ManagedDeviceVector<WarpXParticleContainer*> v_pc_product,
```
Comment (ax3l) [inline Source/Particles/ParticleCreation/ElementaryProcess.H]: wait, that's too much change...

File: Source/Particles/ParticleCreation/ElementaryProcess.H [hunk 2]
```diff
@@ -212,12 +212,11 @@ public:
         amrex::Gpu::ManagedDeviceVector<int> v_pid_product,
         amrex::Gpu::ManagedDeviceVector<WarpXParticleContainer::ParticleType*> v_particles_product,
         WarpXParticleContainer::ParticleType* particles_source,
-        const amrex::Vector<copyParticle>& v_copy_functor,
+        const amrex::Gpu::ManagedDeviceVector<copyParticle>& v_copy_functor,
         amrex::GpuArray<int*,1> runtime_iattribs_source)
     {
         int const * const AMREX_RESTRICT p_is_flagged = is_flagged.dataPtr();
         int const * const AMREX_RESTRICT p_i_product = i_product.dataPtr();
-        copyParticle const * const p_copy_functor = v_copy_functor.data();
```
Comment (ax3l) [inline Source/Particles/ParticleCreation/ElementaryProcess.H]: I am now copying the `ManagedDeviceVector` over to the device. We could probably also just give the `dataPtr()` - is that preferred @atmyers ?

Comment (atmyers) [reply Source/Particles/ParticleCreation/ElementaryProcess.H]: I'm surprised that this works - I guess I don't understand what cuda does when we launch a kernel. Maybe it constructs a deep copy of the Vector on the host in a staging area, the memcopies that to the device? `amrex::Vector` doesn't have any `__device__` constructors.

Comment (ax3l) [reply Source/Particles/ParticleCreation/ElementaryProcess.H]: this is not a `amrex::Vector` anymore but a `amrex::ManagedDeviceVector`. I imagine that the simple default copy constructor is called here which copies over sizes and pointer locations and the data behind the pointers is migrated as usual managed memory.

**Comment by ax3l** [comment]
Actually, let me update this. I do not like it as it's passing the whole container now in terms of safety/documented cuda behavior.

On November 5, 2019 5:57:33 PM PST, Andrew Myers <notifications@github.com> wrote:
>atmyers commented on this pull request.
>
>
>
>>          amrex::GpuArray<int*,1> runtime_iattribs_source)
>     {
>  int const * const AMREX_RESTRICT p_is_flagged = is_flagged.dataPtr();
>    int const * const AMREX_RESTRICT p_i_product = i_product.dataPtr();
>-        copyParticle const * const p_copy_functor =
>v_copy_functor.data();
>
>I'm surprised that this works - I guess I don't understand what cuda
>does when we launch a kernel. Maybe it constructs a deep copy of the
>Vector on the host in a staging area, the memcopies that to the device?
>`amrex::Vector` doesn't have any `__device__` constructors.   
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/ECP-WarpX/WarpX/pull/511#discussion_r342885643

--
Sent from my smartphone.
Please excuse my brevity.

File: Source/Particles/ParticleCreation/ElementaryProcess.H (hunk 2 above)
Comment (lucafedeli88) [reply Source/Particles/ParticleCreation/ElementaryProcess.H]: Actually, If I compile with `DEBUG=TRUE` I get the following error message:
```
./Source/Particles/ParticleCreation/ElementaryProcess.H(238): error: calling a __host__ function("amrex::PODVector<    ::copyParticle,  ::amrex::ManagedArenaAllocator<    ::copyParticle> > ::operator [] const") from a __device__ function(" const") is not allowed

./Source/Particles/ParticleCreation/ElementaryProcess.H(238): error: identifier "amrex::PODVector<    ::copyParticle,  ::amrex::ManagedArenaAllocator<    ::copyParticle> > ::operator [] const" is undefined in device code

./Source/Particles/ParticleCreation/ElementaryProcess.H(247): warning: calling a __host__ function("amrex::PODVector<    ::copyParticle,  ::amrex::ManagedArenaAllocator<    ::copyParticle> > ::PODVector") from a __host__ __device__ function("") is not allowed

./Source/Particles/ParticleCreation/ElementaryProcess.H(247): warning: calling a __host__ function("amrex::PODVector<    ::copyParticle,  ::amrex::ManagedArenaAllocator<    ::copyParticle> > ::PODVector") from a __host__ __device__ function("") is not allowed

./Source/Particles/ParticleCreation/ElementaryProcess.H(247): warning: calling a __host__ function("amrex::PODVector<    ::copyParticle,  ::amrex::ManagedArenaAllocator<    ::copyParticle> > ::~PODVector") from a __host__ __device__ function("") is not allowed
```
This message does not show up if I compile with `DEBUG=FALSE`. However, I am not sure that the issue goes away...

**Comment by MaxThevenet** [comment]
@ax3l do you mean we should wait before merging this PR?

**Comment by MaxThevenet** [comment]
Oh actually we should probably address @lucafedeli88's comment first.

File: Source/Particles/ParticleCreation/ElementaryProcess.H (hunk 2 above)
Comment (ax3l) [reply Source/Particles/ParticleCreation/ElementaryProcess.H]: Yes, that's what I meant in

> Actually, let me update this. I do not like it as it's passing the whole container now in terms of safety/documented cuda behavior.


Update pushed now :)

Comment (ax3l) [reply Source/Particles/ParticleCreation/ElementaryProcess.H]: Looks good now :)

**Comment by MaxThevenet** [comment]
Thanks @ax3l for this PR! I'll merge now.
@lucafedeli88 for some reasons, we cannot always reproduce the tests that you are doing. After this PR is merged, could you re-run the test in `DEBUG` mode that you mentioned earlier, and see if last changes by @ax3l fixed it? Thanks!
