### PR TITLE
Fix parallel hanging in lasy reading

### LINKED ISSUE #4272: Hang on Lassen with Lasy
Using the Lasy package I have tried injecting a laser pulse profile into WarpX but I am again getting hanged results. I assume there is an error or crash that is not getting caught due to the characteristics of Lassen as was previously the case in #4185. I have tried several pulse shape options provided in Lasy but get similar hangs almost immediately, i.e., the output log is:

2: 0: MPI initialized with 128 MPI processes
2: 0: MPI initialized with thread support level 3
2: 0: Initializing CUDA...
2: 0: CUDA initialized with 128 devices.
2: 0: AMReX (23.08-23-gd92232a0c17b) initialized
2: 0: --- INFO    : Found lasy file in RZ geometry
2: 0: --- INFO    : Reading [0, 899] data chunk from test_output_gaussian_00000.h5

### PR DESCRIPTION
**Pull request by RemiLehe**
This is done by properly broadcasting the file geometry information.

Before this, the I/O MPI rank would get `fileGeom = 'thetaMode'`, while the other ranks would get `fileGeom = ''`, which caused a number of issue, including inconsistencies when calling `Bcast`, eventually resulting in the observed hang.

Fixes #4272

### CODE REVIEW

**Comment by RemiLehe** [comment]
Fixes  #4272

File: Source/Laser/LaserProfiles.H [hunk 1]
```diff
@@ -328,14 +328,14 @@ private:
...
-        /** Name of the lasy file geometry ("cartesian" for 3D cartesian or "thetaMode" for RZ) */
-        std::string fileGeom;
         /** Name of the binary file containing the data */
         std::string binary_file_name;
         /** Name of the lasy file containing the data */
         std::string lasy_file_name;
         /** true if the file is in the lasy format, false if it is in the binary format */
         bool file_in_lasy_format;
+        /** lasy file geometry ("cartesian" for 3D cartesian or "thetaMode" for RZ) */
+        int file_in_cartesian_geom;
```
Comment (ax3l) [inline Source/Laser/LaserProfiles.H:338]:
```suggestion
        bool file_in_cartesian_geom;
```

File: Source/Laser/LaserProfilesImpl/LaserProfileFromFile.cpp [hunk 2]
```diff
@@ -150,7 +150,7 @@ WarpXLaserProfiles::FromFileLaserProfile::fill_amplitude (
         "Something bad has happened with the simulation time");
     }
     if (m_params.file_in_lasy_format){
-        if (m_params.fileGeom=="cartesian"){
+        if (m_params.file_in_cartesian_geom==1){
```
Comment (ax3l) [inline Source/Laser/LaserProfilesImpl/LaserProfileFromFile.cpp:153]:
```suggestion
        if (m_params.file_in_cartesian_geom) {
```

File: Source/Laser/LaserProfilesImpl/LaserProfileFromFile.cpp [hunk 3]
```diff
@@ -172,16 +172,17 @@ WarpXLaserProfiles::FromFileLaserProfile::parse_lasy_file(std::string lasy_file_
...
         auto extent = E_laser.getExtent();
         // Extract grid offset and grid spacing
         std::vector<double> offset = E.gridGlobalOffset();
         std::vector<double> position = E_laser.position<double>();
         std::vector<double> spacing = E.gridSpacing<double>();
-        if (m_params.fileGeom=="thetaMode") {
+        if (fileGeom=="thetaMode") {
             //Dimensions of lasy file data: {m,t,r}
             amrex::Print() << Utils::TextMsg::Info( "Found lasy file in RZ geometry" );
+            m_params.file_in_cartesian_geom = 0;
```
Comment (ax3l) [inline Source/Laser/LaserProfilesImpl/LaserProfileFromFile.cpp:185]:
```suggestion
            m_params.file_in_cartesian_geom = false;
```

File: Source/Laser/LaserProfilesImpl/LaserProfileFromFile.cpp [hunk 4]
```diff
@@ -192,9 +193,10 @@ WarpXLaserProfiles::FromFileLaserProfile::parse_lasy_file(std::string lasy_file_
             m_params.t_max = m_params.t_min + (m_params.nt-1)*spacing[0];
             m_params.r_min = offset[1] + position[1]*spacing[1];
             m_params.r_max = m_params.r_min + (m_params.nr-1)*spacing[1];
-        } else if (m_params.fileGeom=="cartesian"){
+        } else if (fileGeom=="cartesian"){
             //Dimensions of lasy file data: {t,y,x}
             amrex::Print() << Utils::TextMsg::Info( "Found lasy file in 3D cartesian geometry");
+            m_params.file_in_cartesian_geom = 1;
```
Comment (ax3l) [inline Source/Laser/LaserProfilesImpl/LaserProfileFromFile.cpp:199]:
```suggestion
            m_params.file_in_cartesian_geom = true;
```

File: Source/Laser/LaserProfilesImpl/LaserProfileFromFile.cpp [hunk 5]
```diff
@@ -214,6 +216,7 @@ WarpXLaserProfiles::FromFileLaserProfile::parse_lasy_file(std::string lasy_file_
     }
 
     //Broadcast parameters
+   ParallelDescriptor::Bcast(&m_params.file_in_cartesian_geom, 1, ParallelDescriptor::IOProcessorNumber());
```
Comment (ax3l) [inline Source/Laser/LaserProfilesImpl/LaserProfileFromFile.cpp:219]:
```suggestion
    ParallelDescriptor::Bcast(&m_params.file_in_cartesian_geom, 1, ParallelDescriptor::IOProcessorNumber());
```

File: Source/Laser/LaserProfilesImpl/LaserProfileFromFile.cpp [hunk 6]
```diff
@@ -316,7 +319,7 @@ WarpXLaserProfiles::FromFileLaserProfile::read_data_t_chunk (int t_begin, int t_
         "Reading [" + std::to_string(i_first) + ", " + std::to_string(i_last) +
             "] data chunk from " + m_params.lasy_file_name);
     int data_size;
-    if (m_params.fileGeom=="thetaMode") {
+    if (m_params.file_in_cartesian_geom==0) {
```
Comment (ax3l) [inline Source/Laser/LaserProfilesImpl/LaserProfileFromFile.cpp:322]:
```suggestion
    if (!m_params.file_in_cartesian_geom) {
```

File: Source/Laser/LaserProfilesImpl/LaserProfileFromFile.cpp [hunk 7]
```diff
@@ -329,7 +332,7 @@ WarpXLaserProfiles::FromFileLaserProfile::read_data_t_chunk (int t_begin, int t_
         auto E = i.meshes["laserEnvelope"];
         auto E_laser = E[io::RecordComponent::SCALAR];
         openPMD:: Extent full_extent = E_laser.getExtent();
-        if (m_params.fileGeom=="thetaMode") {
+        if (m_params.file_in_cartesian_geom==0) {
```
Comment (ax3l) [inline Source/Laser/LaserProfilesImpl/LaserProfileFromFile.cpp:335]:
```suggestion
        if (!m_params.file_in_cartesian_geom) {
```

File: Source/Laser/LaserProfilesImpl/LaserProfileFromFile.cpp [hunk 8]
```diff
@@ -192,9 +193,10 @@ WarpXLaserProfiles::FromFileLaserProfile::parse_lasy_file(std::string lasy_file_
             m_params.t_max = m_params.t_min + (m_params.nt-1)*spacing[0];
             m_params.r_min = offset[1] + position[1]*spacing[1];
             m_params.r_max = m_params.r_min + (m_params.nr-1)*spacing[1];
-        } else if (m_params.fileGeom=="cartesian"){
+        } else if (fileGeom=="cartesian"){
```
Comment (ax3l) [inline Source/Laser/LaserProfilesImpl/LaserProfileFromFile.cpp:196]:
```suggestion
        } else if (fileGeom=="cartesian") {
```

**Comment by ax3l** [comment]
Let's not do my suggestions, AMReX BCast does not support it.

**Review by ax3l — APPROVED** [review]
