### PR TITLE
Fix bug in loop over boxes in WarpX::UpdateAuxilaryDataStagToNodal

### LINKED ISSUE #1554: Loop over boxes in WarpX::UpdateAuxilaryDataStagToNodal
The following change, namely a loop over the cells of a valid box grown by 2 guard cells, was introduced in #1468, as an empirical fix to some bug appearing when running the new Galilean or comoving algorithms with high-order interpolation from staggered to nodal grids (momentum-conserving field gathering):
https://github.com/ECP-WarpX/WarpX/blob/1f8ab0e625f27e9201b0da9dcfbab52c30112089/Source/Parallelization/WarpXComm.cpp#L132-L137

The number of guard cells used here (`2` on line 136) should be understood better and possibly expressed as a function of other similar parameters defined in the class `guardCellManager`. Intuitively, if the guard cells are filled properly after updating the valid cells through this call, it should not be necessary to grow the box and a loop over the cells of the valid box should be sufficient.

### PR DESCRIPTION
**Pull request by EZoni**
This PR should close #1554.

A loop over the valid box (`mfi.validbox()`) only was not possible due to the exterior ghost cells that were not subsequently filled in by calling `FillBoundary`.

Instead of growing the valid box by an _ad hoc_ number of cells, which so far could have been expressed in terms of the orders of the shape factors only (replacing `2` with `WarpX::nox/2+1` and so forth) but in principle could depend on other algorithmic details, I think it is safer to loop over the full box (`mfi.fabbox()`), including ghost cells, and make sure that the input array is padded with zeros beyond ghost cells in order to take care of possible out-of-bound accesses due to the large stencils.

**Update**
I added the bug label, because this seems to fix a bug that became evident only by running the 3D three-stages simulation for the milestone with FDTD and momentum-conserving field gathering.

### CODE REVIEW

File: Source/Parallelization/WarpXComm_K.H [hunk 1]
```diff
@@ -522,6 +522,13 @@ void warpx_interp (const int j,
 {
     using namespace amrex;
 
+    // Pad input array with zeros beyond ghost cells
+    // for out-of-bound accesses due to large-stencil operations
+    const auto arr_safe = [arr_fine] (const int jj, const int kk, const int ll) noexcept
+    {
+        return arr_fine.contains(jj,kk,ll) ? arr_fine(jj,kk,ll) : 0.0_rt;
+    };
+
```
Comment (EZoni) [inline Source/Parallelization/WarpXComm_K.H]: @WeiqunZhang confirmed that this device code for padding should be reasonably fast.

**Review by ax3l — APPROVED** [review]
This looks good to me, but I let someone else check this (I am not too familiar with the WarpXComm change).

Thank you @EZoni! :rocket: :sparkles:

File: Source/Parallelization/WarpXComm_K.H [hunk 2]
```diff
@@ -522,6 +522,13 @@ void warpx_interp (const int j,
 {
     using namespace amrex;
 
+    // Pad input array with zeros beyond ghost cells
+    // for out-of-bound accesses due to large-stencil operations
+    const auto arr_safe = [arr_fine] (const int jj, const int kk, const int ll) noexcept
```
Comment (ax3l) [inline Source/Parallelization/WarpXComm_K.H]: I think this could even be a `constexpr` function
```suggestion
    constexpr auto arr_fine_zeropad = [arr_fine] (const int jj, const int kk, const int ll) noexcept
```

but it probably makes no difference.

For the naming, I would probably call it `arr_fine_zeropad` because that's more descriptive than safe.

Comment (EZoni) [reply Source/Parallelization/WarpXComm_K.H]: Thanks for the suggestions, Axel!

About the variable names, since this is a device kernel, I thought it would be a good idea to use a naming convention that is often used in AMReX kernels, with the tags `src` and `dst` to denote source and destination quantities, respectively. Hence, I renamed the variables as follows:
- `arr_aux` renamed as `dst_arr`
- `arr_fine` renamed as `src_arr`
- `arr_stag` renamed as `src_stag` (since it is the index type of the source MultiFab, the old name was not clear)
- `arr_safe` renamed as `src_arr_zeropad` (with the `zeropad` tag as you suggested)

About the `constexpr`, I could not use it because the compiler says that the type of the variable is not literal, "is a closure type, which is only literal in C++17 and later".

**Review by RemiLehe — APPROVED** [review]
