### PR TITLE
Raise the stack limit when running with cuda

### LINKED ISSUE #1153: GPU launch failure with uniform plasma script in DEBUG mode
I am getting the following error with the `Examples/Physics_applications/uniform_plasma/inputs_3d` file when running with DEBUG=TRUE:

```
STEP 1 starts ...
amrex::Abort::0::CUDA error 719 in file /home/atmyers/AMReX-Codes/amrex//Src/Base/AMReX_GpuDevice.cpp line 587: unspecified launch failure !!
```

This happens both on summit and on my local workstation. Running under `cuda-gdb` reveals:

``` 
CUDA_EXCEPTION_2, Lane User Stack Overflow.
```

Coming from kernel launches where we use the `GetExternalEField` and `GetExternalBField` functors. Commenting out the lines with the parser make this go away. I will address this in a PR.

### PR DESCRIPTION
**Pull request by atmyers**
The `GetExternalEField` and `GetExternalBField` functors use a lot of stack memory, I think because of the use of recursive functions in the parser. This PR proposes that we raise the limit, which fixes #1153. 

In the future, we made to explore alternative approaches to recursive functions - for one thing, DPC++ doesn't support them.

### CODE REVIEW

**Review by LDAmorim — COMMENTED** [review]
Thanks for explaining this @atmyers !

File: Source/main.cpp [hunk 1]
```diff
@@ -34,6 +34,11 @@ int main(int argc, char* argv[])
 
     amrex::Initialize(argc,argv);
 
+    // we need a larger stack limit that usual bc of the parser.
```
Comment (ax3l) [inline Source/main.cpp]:
```suggestion
    // we need a larger stack limit than usual bc of the parser.
```

File: Source/main.cpp [hunk 2]
```diff
@@ -34,6 +34,11 @@ int main(int argc, char* argv[])
...
+#if defined(AMREX_USE_GPU) && defined(AMREX_USE_CUDA)
```
Comment (ax3l) [inline Source/main.cpp]: Is this sufficient?
```suggestion
#if defined(AMREX_USE_CUDA)
```

File: Source/main.cpp [hunk 3]
```diff
@@ -34,6 +34,11 @@ int main(int argc, char* argv[])
...
+    AMREX_CUDA_SAFE_CALL(cudaDeviceSetLimit(cudaLimitStackSize, 20*1024));
```
Comment (ax3l) [inline Source/main.cpp:39]: I am trying to spot the default size on a P100/V100/A100... Do you know?
https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#features-and-technical-specifications

Does increasing this generally lead to a performance drop, e.g. due to limited parallelism?

Comment (WeiqunZhang) [reply Source/main.cpp:39]: I am worried about it too.

Comment (atmyers) [reply Source/main.cpp:39]: The runtime on the uniform plasma benchmark we have been using is exactly the same as if I hack out the parser stuff altogether, so that I can leave the limit alone.

Comment (atmyers) [reply Source/main.cpp:39]: The runtime on the uniform plasma benchmark we have been using is exactly the same as if I hack out the parser stuff altogether, so that I can leave the limit alone.

**Comment by WeiqunZhang** [comment]
There are three parser calls in that function.  If you comment out two, will it work.  If so, we might be able to turn these three calls into a loop and force nvcc to not unroll it.

File: Source/main.cpp (hunk 3 above)
Comment (atmyers) [reply Source/main.cpp:39]: On Summit and my work station anyway, the limit is 6.5 kB.

**Comment by atmyers** [comment]
Note that this is only changed in Debug mode now.

**Review by WeiqunZhang — APPROVED** [review]

**Comment by WeiqunZhang** [comment]
Looks good to me.

There is a `recursion` branch on my fork, https://github.com/WeiqunZhang/WarpX/  Could you give it try to see if it also works?  You will also have to use this. https://github.com/AMReX-Codes/amrex/pull/1111 I will test to see if it works with DPC++.  If so, I will try to see if it causes any performance difference fro WarpX with CUDA.

File: Source/main.cpp (hunk 3 above)
Comment (ax3l) [reply Source/main.cpp:39]: Do you know where the rest of the memory goes to? Is it shared with L1 or shared memory or so? Have not turned that knob before. Let's ping on slack.

Comment (ax3l) [reply Source/main.cpp:39]: Update: ah, with the Debug update it does not really matter now. Now I am just curious (:

**Review by ax3l — APPROVED** [review]

File: Source/main.cpp (hunk 3 above)
Comment (ax3l) [reply Source/main.cpp:39]: paraphrasing @maxpkatz for the sake of googling it myself in a few months:

This is memory reserved for thread-local stack memory. The amount of reserved stack memory is stack memory per thread * number of (potentially) possible resident threads on the device.

The `cudaLimitStackSize` is usually about half of the pre-reserved 300MByte (on a V100) and stored in device DRAM.
If one doubles the stack size, one will double the amount of memory reserved (so one starts with 450 MB gone).

:+1: all clear now.

**Comment by ax3l** [comment]
Thank you for debugging and fixing this @atmyers! :rocket: :sparkles:
