### PR TITLE
openPMD: Handle Zero Particles Well

### LINKED ISSUE #2900: Particle openPMD IO issues when species not present in the first dump
When using openPMD output, if no particles of a species is written at the first dump, the openPMD-viewer cannot read particle data in the later dumps, even if particles are actually dumped. This happens in a wakefield acceleration simulation with a moving window, where the box z dimension is originally (-100.e-6,0) and the plasma starts at 200.e-6 for some reasons.

A reproducer can be found below (using ADIOS2 here, but I think it's the same for HDF5). For a box with z = (-25.e-6,5.e-6), it runs:
- A simulation with plasma electrons starting **in** the box (at z=0.e-6)
- A simulation with plasma electrons starting **out** of the box (at z=10.e-6)

This is done with the following submission script (a few seconds, here on the Juwels Booster):
```sh
#!/bin/bash -l
#SBATCH -A plasmabbq
#SBATCH --partition=booster
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=4
#SBATCH --gres=gpu:4
#SBATCH --time=00:10:00
#SBATCH --job-name=test

source ../profile.sh

EXEC=$HOME/src/warpx/build/bin/warpx.3d.MPI.CUDA.DP.OPMD

srun -n 4 --cpu_bind=sockets $EXEC inputs \
     xz_slice.file_prefix = diags_in/xz_slice \
     yz_slice.file_prefix = diags_in/yz_slice \
     beams.file_prefix = diags_in/beams \
     electrons.zmin = 0.e-6 \
    &> output_in.txt

srun -n 4 --cpu_bind=sockets $EXEC inputs \
     xz_slice.file_prefix = diags_out/xz_slice \
     yz_slice.file_prefix = diags_out/yz_slice \
     beams.file_prefix = diags_out/beams \
     electrons.zmin = 10.e-6 \
    &> output_out.txt
```

After 500 iterations, the box contains electrons in both cases, but only the first run can be properly read by the openPMD-viewer. This can be seen with the following Notebook:
```py
%matplotlib inline
from openpmd_viewer import OpenPMDTimeSeries

iteration = 500

# Works fine
ts_in = OpenPMDTimeSeries('diags_in/beams')
z, = ts_in.get_particle(species='electrons', iteration=iteration, var_list = ['z'])
print(z.shape)

# Gives warnings and errors
ts_out = OpenPMDTimeSeries('diags_out/beams')
z, = ts_out.get_particle(species='electrons', iteration=iteration, var_list = ['z'])
print(z.shape)
```
In the second case, one gets warnings and errors like:
```
Warning: File 200 has different openPMD parameters than the rest of the time series.
OpenPMDException: No particle data in this time series
```
Here is the [input file](https://github.com/ECP-WarpX/WarpX/files/8160908/inputs.txt) used.

### PR DESCRIPTION
**Pull request by ax3l**
When a time step for output encounters zero particles in a species, then we still want to dump them as "empty" species (for a step) in openPMD. That simplifies post-processing a lot and we have the mechanisms in openPMD for it :)

This also enables ADIOS `.bp` support for BTD :)

Fix #2900
Partly a follow-up to #1898, but mostly a missing implementation for zero particle cases.

## To Do

- [x] finalize coding (dump: `makeEmpty()`)
- [x] testing
- [x] fix BTD CI issues
- [x] check if BTD with ADIOS now works, too

### CODE REVIEW

File: Source/Diagnostics/WarpXOpenPMD.cpp [hunk 1]
```diff
@@ -662,161 +664,195 @@ WarpXOpenPMDPlot::DumpToFile (ParticleContainer* pc,
...
+    // define positions & offset structure
+    const unsigned long long NewParticleVectorSize = total_particles + ParticleFlushOffset;
+    // we will set up empty particles unless it's BTD, where we might add some in a following buffer dump
+    //   during this setup, we mark some particle properties as constant and potentially zero-sized
+    m_doParticleSetUp = true;
+    if (isBTD)
+        m_doParticleSetUp = is_first_flush_with_particles || is_last_flush_and_never_particles;
+
+    // this setup stage also implicitly calls "makeEmpty" if needed (i.e., is_last_flush_and_never_particles)
+    SetupPos(currSpecies, NewParticleVectorSize, charge, mass, isBTD);
```
Comment (guj) [inline Source/Diagnostics/WarpXOpenPMD.cpp]: When m_doParticleSetup is false, should it still go to Setup*() functions?

Comment (ax3l) [reply Source/Diagnostics/WarpXOpenPMD.cpp]: yes, there is handling inside them to skip parts if `m_doParticleSetUp` is set.

Comment (guj) [reply Source/Diagnostics/WarpXOpenPMD.cpp]: Yes I saw that.  If m_doParticelSetup =false, why still need to go through part of the Setup*() functions?

Comment (ax3l) [reply Source/Diagnostics/WarpXOpenPMD.cpp]: Good question, I will check if we can skip that altogether and delay it in BTD until we fulfill `m_doParticleSetUp`.

Comment (ax3l) [reply Source/Diagnostics/WarpXOpenPMD.cpp]: Ah, the challenge here is that we need to call this setup multiple times for BTD, since we use it to resize the output as we add more particles to the same step in subsequent calls.

Comment (guj) [reply Source/Diagnostics/WarpXOpenPMD.cpp]: when there is no particle, nothing to adjust?

Comment (ax3l) [reply Source/Diagnostics/WarpXOpenPMD.cpp]: I have to adjust a bit more next week for BTD. Have to move out the declaration of constant records so they only happen once

Comment (ax3l) [reply Source/Diagnostics/WarpXOpenPMD.cpp]: Done :)

File: Source/Diagnostics/WarpXOpenPMD.cpp [hunk 2]
```diff
@@ -662,161 +664,156 @@ WarpXOpenPMDPlot::DumpToFile (ParticleContainer* pc,
...
+    AMREX_ALWAYS_ASSERT(int_comp_names.size() == pc->NumIntComps());
+
+    WarpXParticleCounter counter(pc);
+    auto const num_dump_particles = counter.GetTotalNumParticles();
+
+    openPMD::Iteration currIteration = GetIteration(iteration, isBTD);
+    openPMD::ParticleSpecies currSpecies = currIteration.particles[name];
+
+    // prepare data structures the first time BTD has non-zero particles
+    //   we set some of them to zero extent, so we need to time that welll
```
Comment (RevathiJambunathan) [inline Source/Diagnostics/WarpXOpenPMD.cpp]:
```suggestion
    //   we set some of them to zero extent, so we need to time that well
```

File: Source/Diagnostics/WarpXOpenPMD.cpp [hunk 3]
```diff
@@ -662,161 +664,156 @@ WarpXOpenPMDPlot::DumpToFile (ParticleContainer* pc,
...
+    bool const is_first_flush_with_particles = num_dump_particles > 0 && ParticleFlushOffset == 0;
+    // BTD: we flush multiple times to the same lab step and thus need to resize
+    //   our declared particle output sizes
+    bool const is_resizing_flush = num_dump_particles > 0 && ParticleFlushOffset > 0;
+    // write structure & declare particles in this (lab) step empty:
+    //   if not BTD, then this is the only (and last) time we flush to this step
+    //   if BTD, then we do this multiple times
```
Comment (RevathiJambunathan) [inline Source/Diagnostics/WarpXOpenPMD.cpp]:
```suggestion
    //   if BTD, then we may do this multiple times until it is the last BTD flush
```

File: Source/Diagnostics/WarpXOpenPMD.cpp [hunk 4]
```diff
@@ -662,161 +664,156 @@ WarpXOpenPMDPlot::DumpToFile (ParticleContainer* pc,
...
+    bool const is_last_flush_to_step = !isBTD || (isBTD && isLastBTDFlush);
+    // well, even in BTD we have to recognize that some lab stations have no
```
Comment (RevathiJambunathan) [inline Source/Diagnostics/WarpXOpenPMD.cpp]:
```suggestion
    // well, even in BTD we have to recognize that some lab stations may have no
```

File: Source/Diagnostics/WarpXOpenPMD.cpp [hunk 5]
```diff
@@ -662,161 +664,156 @@ WarpXOpenPMDPlot::DumpToFile (ParticleContainer* pc,
...
+    // define positions & offset structure
+    const unsigned long long NewParticleVectorSize = num_dump_particles + ParticleFlushOffset;
+    // we will set up empty particles unless it's BTD, where we might add some in a following buffer dump
+    //   during this setup, we mark some particle properties as constant and potentially zero-sized
+    bool doParticleSetup = true;
+    if (isBTD)
+        doParticleSetup = is_first_flush_with_particles || is_last_flush_and_never_particles;
+
+    // this setup stage also implicitly calls "makeEmpty" if needed (i.e., is_last_flush_and_never_particles)
+    //   for BTD, we call this multiple times as we will resize in subsequent dumps
```
Comment (RevathiJambunathan) [inline Source/Diagnostics/WarpXOpenPMD.cpp]:
```suggestion
    //   for BTD, we call this multiple times as we may resize in subsequent dumps if number of particles in the buffer > 0
```

**Review by RevathiJambunathan — COMMENTED** [review]
This looks good to me. 
Thank you for this PR @ax3l !
I have minor suggestions in the comments

**Review by RevathiJambunathan — APPROVED** [review]

File: Source/Diagnostics/WarpXOpenPMD.cpp [hunk 6]
```diff
@@ -976,51 +970,110 @@ void
...
+    }
+
+    // make constant
+    using namespace amrex::literals;
+    auto const scalar = openPMD::RecordComponent::SCALAR;
+    for( auto const& comp : positionComponents ) {
+        currSpecies["positionOffset"][comp].makeConstant( 0._prt );
+    }
+    currSpecies["charge"][scalar].makeConstant( charge );
+    currSpecies["mass"][scalar].makeConstant( mass );
```
Comment (ax3l) [inline Source/Diagnostics/WarpXOpenPMD.cpp:1010]: Oops, 2x forgot `resetDataset`. Fixed in #3451
