### PR TITLE
Load Particles: external_file MPI Support

### LINKED ISSUE #952: Read particle data from openPMD - crash if parallel
Hi all,

I have been running the following external `openPMD` particle properties file [e-_primary_s1_opmd.h5.zip](https://github.com/ECP-WarpX/WarpX/files/4537894/e-_primary_s1_opmd.h5.zip) with the current master branch, using the input file 
[input_script.txt](https://github.com/ECP-WarpX/WarpX/files/4540668/input_script.txt)

I found that parallelization leads to coach:
- if I ran it on only 1 single MPI rank, then the simulation runs well and I get the desired output. I.e. correct particle data in the plotfiles, the run completes all the steps and generates the tiny profilers.
- if I play with the `amr.blocking_factor` and make it and `amr.max_grid_size` =32 (i.e. generating only 1 grid or 1 box), [input_script.txt](https://github.com/ECP-WarpX/WarpX/files/4540719/input_script.txt), then the run also goes well.
- If instead I ran on multiple ranks with multiple grids or boxes, the simulation crashes (after injecting a number of particles that changes each time I run exactly the same run with the same nr of nodes). Looking at the plotfiles, the particle position data is correct. The momentum of some particles is 0 (not set).

For comparison, I tested the executable running a `Gaussian` beam identical input file and saw no issue. The `openPMD` particle external file module is based on the Gaussian one.

I tried to debug this using the `DEBUG=TRUE` flag when compiling WarpX.
Depending on weather I would use 2 or 4 nodes, with `amr.blocking_factor` below `amr.max_grid_size`, I would either see only `SIGABORT` or `segfault` or the error message:
```
===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   PID 5554 RUNNING AT LDianaAmorim-M30
=   EXIT CODE: 6
=   CLEANING UP REMAINING PROCESSES
=   YOU CAN IGNORE THE BELOW CLEANUP MESSAGES
===================================================================================
YOUR APPLICATION TERMINATED WITH THE EXIT STRING: Abort trap: 6 (signal 6)
This typically refers to a problem with your application.
Please see the FAQ page for debugging suggestions
```
and sometimes I had `Backtrace` files. Sometimes those files had information that pointed to the CurrentDeposition.H file. 

It seems that the issue, whenever I use multiple boxes, comes from the particle momentum making this line out of bound: https://github.com/ECP-WarpX/WarpX/blob/377568fa95c1c19f4e0f7868b6704ca35b0ba942/Source/Particles/Deposition/CurrentDeposition.H#L453

I think that maybe it is because although I set the read and write in the function `AddPlasmaFromFile`of `PhysicalParticleContainer.cpp` to happen in only 1 MPI rank. The momentum part might be affecting other ranks and it is used to do the current deposition.

Do any of you have any suggestion to what might cause this issue?

Thanks,
Diana

ps: Sorry @ax3l if you explained this to me on Friday, but I probably made a confusion about it during the weekend. And sorry for not pinging you about this during the weekend, but I took time to understand this crash.

### PR DESCRIPTION
**Pull request by ax3l**
Split and add MPI support for particle loading from an openPMD file.

Changes input file to allow overwriting the charge and mass by user input.
Allows to add "weighting" to files as constant record (ED-PIC extension).

Fixes build errors with openPMD enabled and RZ (but no full read runtime support yet).

## Check List

- [x] deactivated compile (2D, 3D)
- [x] activated compile (2D, 3D)
- [x] runtime test: 3D3V with 4 MPI ranks,  2D3V with 4 MPI ranks, RZ: unclear to me if this worked, but guarded in input checks for now and does not crash

Close #952

### CODE REVIEW

File: Source/Particles/PhysicalParticleContainer.cpp [hunk 1]
```diff
@@ -341,51 +345,50 @@ PhysicalParticleContainer::AddPlasmaFromFile(const std::string s_f,
...
-        amrex::ParticleReal p_q = ps.second["charge"][openPMD::RecordComponent::SCALAR].loadChunk<amrex::ParticleReal>().get()[0];
-        double const charge_unit = ps.second["charge"][openPMD::RecordComponent::SCALAR].unitSI();
+        AMREX_ALWAYS_ASSERT_WITH_MESSAGE(plasma_injector,
+                                         "AddPlasmaFromFile: plasma injector not initialized.\n");
+        // take ownership of the series and close it when done
+        auto series = std::move(plasma_injector->m_openpmd_input_series);
+
+        // assumption asserts: see PlasmaInjector
+        openPMD::Iteration it = series->iterations.begin()->second;
+        openPMD::ParticleSpecies ps = it.particles.begin()->second;
```
Comment (MaxThevenet) [inline Source/Particles/PhysicalParticleContainer.cpp:355]:
```suggestion
        openPMD::Iteration const it = series->iterations.begin()->second;
        openPMD::ParticleSpecies const ps = it.particles.begin()->second;
```
Just asking

File: Source/Initialization/PlasmaInjector.cpp [hunk 2]
```diff
@@ -105,9 +106,61 @@ PlasmaInjector::PlasmaInjector (int ispecies, const std::string& name)
...
+            openPMD::Iteration it = m_openpmd_input_series->iterations.begin()->second;
+            AMREX_ALWAYS_ASSERT_WITH_MESSAGE(
+                it.particles.size() == 1u,
+                "External file should contain only 1 species\n");
+            openPMD::ParticleSpecies ps = it.particles.begin()->second;
+
+            // TODO: Add ASSERT_WITH_MESSAGE to test if mass and charge are constant records
+            if (!charge_is_specified) {
+                amrex::ParticleReal const p_q = ps["charge"][openPMD::RecordComponent::SCALAR].loadChunk<amrex::ParticleReal>().get()[0];
+                double const charge_unit = ps["charge"][openPMD::RecordComponent::SCALAR].unitSI();
```
[the remark this answers is not in the document]
Comment (ax3l) [reply Source/Initialization/PlasmaInjector.cpp:140]: Thanks and good point: the base standard does not require this. So we should check and go on, because our users can still set the charge via the input file option. Will update.

File: Source/Initialization/PlasmaInjector.cpp [hunk 3]
```diff
@@ -105,9 +106,61 @@ PlasmaInjector::PlasmaInjector (int ispecies, const std::string& name)
...
+        } // IOProcessor
+
+        if (!charge_is_specified && !mass_is_specified) {
+            // Broadcast charge and mass to non-IO processors
+            amrex::ParticleReal charge_mass[2] = {charge, mass};
+            ParallelDescriptor::Bcast(charge_mass, 2,
+                ParallelDescriptor::IOProcessorNumber());
+            charge = charge_mass[0];
+            mass = charge_mass[1];
+        }
```
[the remark this answers is not in the document]
Comment (ax3l) [reply Source/Initialization/PlasmaInjector.cpp:157]: What I do here is: if both of these var are overwritten anyway, then we do not have to communicate them first. If at least one of them is not overwritten, we communicate both.

File: Source/Initialization/PlasmaInjector.cpp [hunk 4]
```diff
@@ -119,17 +172,11 @@ PlasmaInjector::PlasmaInjector (int ispecies, const std::string& name)
...
         Print()<<"         The charge in <species>.mass overwrite the one from <species>.species_type\n";
     }
-    if (!charge_is_specified && !species_is_specified){
-        //No need for charge/species definition if external file is used
-        std::string s_inj_style;
-        pp.query("injection_style", s_inj_style);
-        if (s_inj_style != "external_file") {
-            amrex::Abort("Need to specify at least one of species_type or charge");
-        }
+    if (!charge_is_specified && !species_is_specified && s_inj_style != "external_file"){
```
[the remark this answers is not in the document]
Comment (ax3l) [reply Source/Initialization/PlasmaInjector.cpp:175]: only if we enforce the charge above is set, right!

File: Source/Particles/PhysicalParticleContainer.cpp [hunk 5]
```diff
@@ -341,51 +345,50 @@ PhysicalParticleContainer::AddPlasmaFromFile(const std::string s_f,
...
-
-        //TODO: Add ASSERT_WITH_MESSAGE to test if mass and charge are both const
-        amrex::ParticleReal p_m = ps.second["mass"][openPMD::RecordComponent::SCALAR].loadChunk<amrex::ParticleReal>().get()[0];
-        double const mass_unit = ps.second["mass"][openPMD::RecordComponent::SCALAR].unitSI();
-        amrex::ParticleReal p_q = ps.second["charge"][openPMD::RecordComponent::SCALAR].loadChunk<amrex::ParticleReal>().get()[0];
-        double const charge_unit = ps.second["charge"][openPMD::RecordComponent::SCALAR].unitSI();
+        AMREX_ALWAYS_ASSERT_WITH_MESSAGE(plasma_injector,
+                                         "AddPlasmaFromFile: plasma injector not initialized.\n");
+        // take ownership of the series and close it when done
+        auto series = std::move(plasma_injector->m_openpmd_input_series);
```
[the remark this answers is not in the document]
Comment (ax3l) [reply Source/Particles/PhysicalParticleContainer.cpp:351]: We intentionally:
```
// take ownership of the series and close it when done
```
:)

File: Source/Particles/PhysicalParticleContainer.cpp (hunk 1 above)
Comment (ax3l) [reply Source/Particles/PhysicalParticleContainer.cpp:355]: Yeah, I tried with `cbegin` and `const`... but it's hard to implement `loadChunk` in the API as `const` member function, so I cannot constify here :'(

File: Source/Initialization/PlasmaInjector.cpp (hunk 3 above)
[the remark this answers is not in the document]
Comment (MaxThevenet) [reply Source/Initialization/PlasmaInjector.cpp:157]: Wouldn't the behavior you describe happen with
```c++
if (!charge_is_specified || !mass_is_specified)
```
instead of
```c++
if (!charge_is_specified && !mass_is_specified)
```
?
Anyway, let me know when I can re-review :).

File: Source/Particles/PhysicalParticleContainer.cpp (hunk 5 above)
[the remark this answers is not in the document]
Comment (MaxThevenet) [reply Source/Particles/PhysicalParticleContainer.cpp:351]: Yeah, I did read that the first time, but I do not know what closing a series means, sorry :confused:. Is there a pointer `delete` operation at the end?

File: Docs/source/running_cpp/parameters.rst [hunk 6]
```diff
@@ -309,7 +309,8 @@ Particle initialization
       It requires the additional arguments:
       ``<species_name>.injection_file`` (`string`) openPMD file name and
       ``<species_name>.q_tot`` (`double`) optional (default is ``q_tot=0`` and no re-scaling is done, ``weight=q_p``) when specified it is used to re-scale the weight of externally loaded ``N`` physical particles, each of charge ``q_p``, to inject macroparticles of ``weight=<species_name>.q_tot/q_p/N``.
```
Comment (LDAmorim) [inline Docs/source/running_cpp/parameters.rst:311]: If you want to include the other sentence as is then I suggest adding here:
```suggestion
      ``<species_name>.q_tot`` (`double`) optional (default is ``q_tot=0`` and no re-scaling is done, ``weight=q_p``) when specified it is used to re-scale the weight of externally loaded ``N`` physical particles, each of charge ``q_p``, to inject macroparticles of ``weight=<species_name>.q_tot/q_p/N``.
      ``<species_name>.charge`` (`double`) optional (default is read from openPMD file) when set this will be the charge of the physical particle represented by the injected macroparticles.
      ``<species_name>.mass`` (`double`) optional (default is read from openPMD file) when set this will be the charge of the physical particle represented by the injected macroparticles.
```

File: Source/Initialization/PlasmaInjector.cpp (hunk 4 above)
[the remark this answers is not in the document]
Comment (LDAmorim) [reply Source/Initialization/PlasmaInjector.cpp:175]: I think I would keep the option of reading the particle type from the file. Because I wish to introduce multiple (>30) files and not make mistakes.

File: Source/Particles/PhysicalParticleContainer.cpp [hunk 7]
```diff
@@ -341,51 +345,50 @@ PhysicalParticleContainer::AddPlasmaFromFile(const std::string s_f,
...
+        series->flush();
 
         amrex::Real weight;
-        if (q_tot != 0.0){
-            weight = q_tot/(p_q*amrex::Real(npart));
+        if (q_tot != 0.0) {
+            weight = std::abs(q_tot) / ( std::abs(charge) * amrex::Real(npart) );
+        }
+        // ED-PIC extension?
+        else if (ps.contains("weighting")) {
```
Comment (LDAmorim) [inline Source/Particles/PhysicalParticleContainer.cpp:383]: This is a cool idea.
Just to double check, Is "weighting" the name for the output of WarpX in openPMD?

Comment (ax3l) [reply Source/Particles/PhysicalParticleContainer.cpp:383]: Yep, weighting is a concept introduced in the `ED-PIC` extension in openPMD. It has a bit more to it but can likely be present if we get data in, so I just check for it.

Sorry for the broken rendering, GitHub changed the markdown spec at some point:
https://github.com/openPMD/openPMD-standard/blob/1.1.0/EXT_ED-PIC.md#additional-attributes-for-each-particle-record

Comment (LDAmorim) [reply Source/Particles/PhysicalParticleContainer.cpp:383]: That's excellent! Ok I can re-organize the output in my code to contain it too.
Sorry, I did read this openPMD doc a long time ago, but forgot to re-check it recently.
It's super clear! Thank you @ax3l !

File: Source/Particles/PhysicalParticleContainer.cpp (hunk 1 above)
Comment (LDAmorim) [reply Source/Particles/PhysicalParticleContainer.cpp:355]: Maybe this was why I was also having trouble using `const` in the initial PR. Thanks for explaining it!

File: Docs/source/running_cpp/parameters.rst [hunk 8]
```diff
@@ -309,7 +309,8 @@ Particle initialization
...
-      The external file should include the species ``openPMD::Record`` s labeled ``mass`` and ``charge`` (`double` scalars) and also the ``position`` and ``momentum`` (`double` arrays), with dimensionality and units set via ``openPMD::setUnitDimension`` and ``setUnitSI``.
+      The external file must include the species ``openPMD::Record``s labeled ``position`` and ``momentum`` (`double` arrays), with dimensionality and units set via ``openPMD::setUnitDimension`` and ``setUnitSI``.
+      If the external file also contains ``openPMD::Records``s for ``mass`` and ``charge`` (constant `double` scalars) then the species will use these, unless overwritten in the input file (see ``<species_name>.mass``, ```<species_name>.charge`` or ```<species_name>.species_type``).
```
[the remark this answers is not in the document]
Comment (ax3l) [reply Docs/source/running_cpp/parameters.rst:313]: I think we want to allow overwriting, as you currently do. By default it will be read from the file.

[the remark this answers is not in the document]
Comment (LDAmorim) [reply Docs/source/running_cpp/parameters.rst:313]: Good point! Yes

File: Source/Initialization/PlasmaInjector.cpp (hunk 3 above)
[the remark this answers is not in the document]
Comment (ax3l) [reply Source/Initialization/PlasmaInjector.cpp:157]: oh oh -.- negations are hard :hear_no_evil:

File: Source/Initialization/PlasmaInjector.cpp (hunk 4 above)
[the remark this answers is not in the document]
Comment (ax3l) [reply Source/Initialization/PlasmaInjector.cpp:175]: Actually, with the logic update now this part will stay. will push after lunch.

File: Source/Initialization/PlasmaInjector.cpp [hunk 9]
```diff
@@ -141,13 +188,9 @@ PlasmaInjector::PlasmaInjector (int ispecies, const std::string& name)
...
         Print()<<"         The mass in <species>.mass overwrite the one from <species>.species_type\n";
     }
-    if (!mass_is_specified && !species_is_specified){
-        //No need for mass/species definition if external file is used
-        std::string s_inj_style;
-        pp.query("injection_style", s_inj_style);
-        if (s_inj_style != "external_file") {
-            amrex::Abort("Need to specify at least one of species_type or mass");
-        }
+    if (!mass_is_specified && !species_is_specified && s_inj_style != "external_file"){
```
[the remark this answers is not in the document]
Comment (ax3l) [reply Source/Initialization/PlasmaInjector.cpp:191]: will stay this way with logic update. moving the injection loads down.

File: Source/Particles/PhysicalParticleContainer.cpp (hunk 5 above)
[the remark this answers is not in the document]
Comment (ax3l) [reply Source/Particles/PhysicalParticleContainer.cpp:351]: `std::unique_ptrs` do `delete` the memory they own on destruction. they basically save us from ever writing `new` or `delete` again because their lifetime (or a `.reset()` call) determines the lifetime of the memory they own.

File: Source/Particles/PhysicalParticleContainer.cpp (hunk 1 above)
Comment (ax3l) [reply Source/Particles/PhysicalParticleContainer.cpp:355]: Yep, sorry for that. I/O has too much internal state to allow us to make these `const` member functions in openPMD-api atm :cry:

File: Source/Particles/PhysicalParticleContainer.cpp (hunk 7 above)
Comment (ax3l) [reply Source/Particles/PhysicalParticleContainer.cpp:383]: Oh no, this is just an update, don't worry :)

File: Source/Particles/PhysicalParticleContainer.cpp [hunk 10]
```diff
@@ -341,51 +345,50 @@ PhysicalParticleContainer::AddPlasmaFromFile(const std::string s_f,
...
+            // TODO: Add ASSERT_WITH_MESSAGE to test if weighting is a constant record
+            amrex::ParticleReal w = ps["weighting"][openPMD::RecordComponent::SCALAR].loadChunk<amrex::ParticleReal>().get()[0];
```
Comment (ax3l) [inline Source/Particles/PhysicalParticleContainer.cpp:385]: @LDAmorim: "you should warn here as well, if `q_tot` is set :)"

Comment (ax3l) [reply Source/Particles/PhysicalParticleContainer.cpp:385]: - also add assert for `macroWeighted`

File: Source/Particles/PhysicalParticleContainer.cpp [hunk 11]
```diff
@@ -341,51 +347,56 @@ PhysicalParticleContainer::AddPlasmaFromFile(const std::string s_f,
...
-        auto const npart = ps.second["position"]["x"].getExtent()[0];
-        std::shared_ptr<amrex::ParticleReal> ptr_x = ps.second["position"]["x"].loadChunk<amrex::ParticleReal>();
-        double const position_unit_x = ps.second["position"]["x"].unitSI();
-        std::shared_ptr<amrex::ParticleReal> ptr_z = ps.second["position"]["z"].loadChunk<amrex::ParticleReal>();
-        double const position_unit_z = ps.second["position"]["z"].unitSI();
-        std::shared_ptr<amrex::ParticleReal> ptr_ux = ps.second["momentum"]["x"].loadChunk<amrex::ParticleReal>();
-        double const momentum_unit_x = ps.second["momentum"]["x"].unitSI();
-        std::shared_ptr<amrex::ParticleReal> ptr_uz = ps.second["momentum"]["z"].loadChunk<amrex::ParticleReal>();
-        double const momentum_unit_z = ps.second["momentum"]["z"].unitSI();
+        auto const npart = ps["position"]["x"].getExtent()[0];
```
Comment (ax3l) [inline Source/Particles/PhysicalParticleContainer.cpp:361]: - `npart` is unconditionally used which breaks RZ builds

File: Source/Particles/PhysicalParticleContainer.cpp [hunk 12]
```diff
@@ -341,51 +347,56 @@ PhysicalParticleContainer::AddPlasmaFromFile(const std::string s_f,
...
+                                         "AddPlasmaFromFile: plasma injector not initialized.\n");
+        // take ownership of the series and close it when done
+        auto series = std::move(plasma_injector->m_openpmd_input_series);
+
+        // assumption asserts: see PlasmaInjector
+        openPMD::Iteration it = series->iterations.begin()->second;
+        std::string const ps_name = it.particles.begin()->first;
+        openPMD::ParticleSpecies ps = it.particles.begin()->second;
+
 #   if (defined WARPX_DIM_3D) || (defined WARPX_DIM_XZ)
```
Comment (ax3l) [inline Source/Particles/PhysicalParticleContainer.cpp:360]: redundant check:
```suggestion
#   ifdef WARPX_DIM_XZ
```

File: Source/Particles/PhysicalParticleContainer.cpp (hunk 11 above)
Comment (LDAmorim) [reply Source/Particles/PhysicalParticleContainer.cpp:361]: Does this mean we can just add if conditions to make it work in RZ?

File: Source/Particles/PhysicalParticleContainer.cpp (hunk 12 above)
Comment (LDAmorim) [reply Source/Particles/PhysicalParticleContainer.cpp:360]: Good catch! :D

File: Source/Particles/PhysicalParticleContainer.cpp [hunk 13]
```diff
@@ -341,51 +347,56 @@ PhysicalParticleContainer::AddPlasmaFromFile(const std::string s_f,
...
-        mass=p_m*mass_unit;
-        charge=p_q*charge_unit;
+        series->flush();
 
         amrex::Real weight;
-        if (q_tot != 0.0){
-            weight = q_tot/(p_q*amrex::Real(npart));
+        if (q_tot != 0.0) {
+            weight = std::abs(q_tot) / ( std::abs(charge) * amrex::Real(npart) );
+            if (ps.contains("weighting"))
```
Comment (LDAmorim) [inline Source/Particles/PhysicalParticleContainer.cpp:384]: Perfect! Thank you for adding this @ax3l !! :)
```suggestion
            if (ps.contains("weighting")) {
```

File: Source/Particles/PhysicalParticleContainer.cpp [hunk 14]
```diff
@@ -341,51 +347,56 @@ PhysicalParticleContainer::AddPlasmaFromFile(const std::string s_f,
...
+                Print() << "WARNING: Both '" << ps_name << ".q_tot' and '"
+                        << ps_name << ".injection_file' specify a total charge.\n'"
+                        << ps_name << ".q_tot' will take precedence.\n";
```
Comment (LDAmorim) [inline Source/Particles/PhysicalParticleContainer.cpp:387]:
```suggestion
                        << ps_name << ".q_tot' will take precedence.\n";
                        }
```
I'm adding this since when we had the workshop with @MaxThevenet or a WarpX meeting (I think we mentioned it in both) we decided to add the brackets always so people who'd later add to the if statement wouldn't break it. Feel free to disregard if this changed.

Comment (ax3l) [reply Source/Particles/PhysicalParticleContainer.cpp:387]: works for me, sure :)

File: Source/Particles/PhysicalParticleContainer.cpp (hunk 11 above)
Comment (ax3l) [reply Source/Particles/PhysicalParticleContainer.cpp:361]: Fixing this will not yet make it work (at runtime) in RZ, but it should not crash the build :)

File: Source/Particles/PhysicalParticleContainer.cpp [hunk 15]
```diff
@@ -341,51 +347,56 @@ PhysicalParticleContainer::AddPlasmaFromFile(const std::string s_f,
...
         amrex::Abort("AddPlasmaFromFile is only implemented for 2D and 3D\n");
 #   endif
 #   if (defined WARPX_DIM_3D)
-        std::shared_ptr<amrex::ParticleReal> ptr_y = ps.second["position"]["y"].loadChunk<amrex::ParticleReal>();
-        double const position_unit_y = ps.second["position"]["y"].unitSI();
-        std::shared_ptr<amrex::ParticleReal> ptr_uy = ps.second["momentum"]["y"].loadChunk<amrex::ParticleReal>();
-        double const momentum_unit_y = ps.second["momentum"]["y"].unitSI();
+        std::shared_ptr<amrex::ParticleReal> ptr_y = ps["position"]["y"].loadChunk<amrex::ParticleReal>();
+        double const position_unit_y = ps["position"]["y"].unitSI();
+        std::shared_ptr<amrex::ParticleReal> ptr_uy = ps["momentum"]["y"].loadChunk<amrex::ParticleReal>();
```
Comment (ax3l) [inline Source/Particles/PhysicalParticleContainer.cpp:376]: uy is present in 2D3V as well :)

**Comment by LDAmorim** [comment]
Thanks for the changes in the PR @ax3l !
Maybe can you post the results of the tests you did?
It might be very useful for us to use for testing any future changes?

File: Docs/source/running_cpp/parameters.rst [hunk 16]
```diff
@@ -309,7 +309,10 @@ Particle initialization
...
-      The external file should include the species ``openPMD::Record`` s labeled ``mass`` and ``charge`` (`double` scalars) and also the ``position`` and ``momentum`` (`double` arrays), with dimensionality and units set via ``openPMD::setUnitDimension`` and ``setUnitSI``.
+      ``<species_name>.charge`` (`double`) optional (default is read from openPMD file) when set this will be the charge of the physical particle represented by the injected macroparticles.
+      ``<species_name>.mass`` (`double`) optional (default is read from openPMD file) when set this will be the charge of the physical particle represented by the injected macroparticles.
+      The external file must include the species ``openPMD::Record``s labeled ``position`` and ``momentum`` (`double` arrays), with dimensionality and units set via ``openPMD::setUnitDimension`` and ``setUnitSI``.
+      If the external file also contains ``openPMD::Records``s for ``mass`` and ``charge`` (constant `double` scalars) then the species will use these, unless overwritten in the input file (see ``<species_name>.mass``, ```<species_name>.charge`` or ```<species_name>.species_type``).
```
Comment (LDAmorim) [inline Docs/source/running_cpp/parameters.rst:315]: Do you want to add also the description for the `weighting` part?
Since the option to read it is included too in the code.

Comment (ax3l) [reply Docs/source/running_cpp/parameters.rst:315]: Duh, yes...
Hm, it's a bit of a special feature for special files (ED-PIC only) and only a preview, let's not expose it to users yet and do it in a follow-up.

**Comment by ax3l** [comment]
Forgot to document:
> Maybe can you post the results of the tests you did?
> It might be very useful for us to use for testing any future changes?

I used @LDAmorim's Geant4 input and made sure 2D and 3D sims load and propagate all loaded particles with her scripts :)
