### PR TITLE
Fix a runtime parameter issue in time-averaged diagnostics

### LINKED ISSUE #5751: Constant `clight` not recognized
## Description
I'm not sure if this is a bug or a misunderstanding. I defined a constant in the input file
`my_constants.omega0 = 2 * pi * clight / lambda0`
based on the [input guide](https://warpx.readthedocs.io/en/latest/usage/parameters.html#warpx-constants), which says that some universal constants are available for parsing.
However, the code crashed at start complaining that `clight` wasn't defined. Am I doing something wrong?
The specific error message is
`amrex::Error::15444::ParmParse: failed to parse 2*pi*clight/lambda0 due to unknown symbol clight !!!`
This is based on WarpX `25.03`.

### PR DESCRIPTION
**Pull request by WeiqunZhang**
Use `utils::parser::queryWithParser` instead of vanilla `amrex::Parser`, because latter does not know WarpX's constants unless it's informed.

Fix #5751

### CODE REVIEW

File: Source/Diagnostics/FullDiagnostics.cpp [hunk 1]
```diff
@@ -155,9 +156,8 @@ FullDiagnostics::ReadParameters ()
         const bool averaging_period_steps_specified = pp_diag_name.query(
                 "average_period_steps", m_average_period_steps
         );
-        const bool averaging_period_time_specified = pp_diag_name.queryWithParser(
-                "average_period_time", m_average_period_time
-        );
+        const bool averaging_period_time_specified = utils::parser::queryWithParser
```
Comment (ax3l) [inline Source/Diagnostics/FullDiagnostics.cpp:158]: Temporary work-around until we have #5254

**Review by ax3l — APPROVED** [review]
