### PR TITLE
ADIOS2: Fix BTD Particle Resize w/ Empty Ranks

### LINKED ISSUE #3389: BackTransformDiagnostics: position offset does not have consistent number of macroparticle
When running this input file:
[inputs.txt](https://github.com/ECP-WarpX/WarpX/files/9552278/inputs.txt)
it seems that the metadata of the BackTransformed diagnostics is inconsistent. For instance, running the following Python code:
```python
from openpmd_viewer import OpenPMDTimeSeries
ts = OpenPMDTimeSeries('./diags/diag_btd/')
ts.get_particle(['x'], iteration=3)
```
results in the following error:
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-3-4c6f54023500> in <module>
----> 1 ts.get_particle(['x'], iteration=3)

~/miniconda3/lib/python3.9/site-packages/openpmd_viewer/openpmd_timeseries/main.py in get_particle(self, var_list, species, t, iteration, select, plot, nbins, plot_range, use_field_mesh, histogram_deposition, **kw)
    272         data_list = []
    273         for quantity in var_list:
--> 274             data_list.append( self.data_reader.read_species_data(
    275                 iteration, species, quantity, self.extensions))
    276         # Apply selection if needed

~/miniconda3/lib/python3.9/site-packages/openpmd_viewer/openpmd_timeseries/data_reader/data_reader.py in read_species_data(self, iteration, species, record_comp, extensions)
    281                     filename, iteration, species, record_comp, extensions )
    282         elif self.backend == 'openpmd-api':
--> 283             return io_reader.read_species_data(
    284                     self.series, iteration, species, record_comp, extensions )
    285 

~/miniconda3/lib/python3.9/site-packages/openpmd_viewer/openpmd_timeseries/data_reader/io_reader/particle_reader.py in read_species_data(series, iteration, species_name, component_name, extensions)
     87     if component_name in ['x', 'y', 'z']:
     88         offset = get_data(series, species['positionOffset'][component_name])
---> 89         data += offset
     90     # - Return momentum in normalized units
     91     elif component_name in ['ux', 'uy', 'uz' ]:

ValueError: operands could not be broadcast together with shapes (41886,) (41894,) (41886,) 
```

### PR DESCRIPTION
**Pull request by ax3l**
For ADIOS2 BP4 and BP5 particle BTD writes, setting an update of a variable's (openPMD record's) shape is not sufficient to drop all meta-data on disk. In situations where the last write to a BTD stage only adds further particles from a few ranks, we need to pad with zero-block writes so ADIOS2 `Put` gets called.

Backend details:
- BP4 (as of ADIOS 2.8): last MPI rank's `Put` meta-data wins
- BP5 (as of ADIOS 2.8): everyone has to write an empty block

## Tests

6 MPI ranks w/ CUDA on Summit  with read-back as in https://github.com/ECP-WarpX/WarpX/issues/3389

- Inputs: [inputs.txt](https://github.com/ECP-WarpX/WarpX/files/10552060/inputs.6.txt)
- Run: `jsrun -r 6 -a 1 -g 1 -c 7 -l GPU-CPU -d packed -b rs --smpiargs="-gpu" ./warpx.RZ.MPI.CUDA.DP.PDP.OPMD.PSATD.QED inputs.txt`
- Test command: `python3 -c "from openpmd_viewer import OpenPMDTimeSeries; ts = OpenPMDTimeSeries('./diags/diag_btd/'); ts.get_particle(['x'], iteration=1)"`

Results:
- [x] reproduced on `development`
- [x] same test, with PR applied, passed
- [ ] same test, with PR applied, and with compression operators (blosc) enabled, passed
  - [x] ADIOS 2.7.1: fails during write
  - [x] ADIOS 2.8.1: fails during write
  - [x] ADIOS 2.8.3 w/ c-blosc 1.21.0: fails during write https://github.com/ornladios/ADIOS2/issues/3460
  - [x] ADIOS `master` as of `98bef0ee88838c034832a1e280dfd555841462dc` w/ c-blosc 2.6.1: also fails

Requires this patch in openPMD-viewer: https://github.com/openPMD/openPMD-viewer/pull/355

## Related Issues

- fix #3389
- https://github.com/ECP-WarpX/WarpX/pull/1898#discussion_r745008290
- https://github.com/ornladios/ADIOS2/issues/3455
- https://github.com/openPMD/openPMD-api/issues/1147

### CODE REVIEW

File: Source/Diagnostics/WarpXOpenPMD.cpp [hunk 1]
```diff
@@ -754,7 +754,16 @@ WarpXOpenPMDPlot::DumpToFile (ParticleContainer* pc,
...
+            //   https://github.com/ECP-WarpX/WarpX/pull/1898#discussion_r745008290
+            // unless we append in ADIOS2:
+            //   https://github.com/ECP-WarpX/WarpX/issues/3389
+            //   https://github.com/ornladios/ADIOS2/issues/3455
+            //   BP4 (ADIOS 2.8): last MPI rank's `Put` meta-data wins
+            //   BP5 (ADIOS 2.8): everyone has to write an empty block
+            bool write_empty_blocks = false;
+            if (m_Series->backend() == "ADIOS2")
+                write_empty_blocks = isBTD;
+            if (numParticleOnTile == 0 && !write_empty_blocks) continue;
```
Comment (ax3l) [inline Source/Diagnostics/WarpXOpenPMD.cpp]: Additional problem to solve: the `pti` loop is skipped altogether if there are no particles in tiles on this level.

**Review by RemiLehe — APPROVED** [review]

**Comment by ax3l** [comment]
We should try if with ADIOS 2.9.0+ this work-around is still needed for BP5:
https://github.com/ornladios/ADIOS2/pull/3562
